import type { ReviewPost } from './types'

export const REVIEW_POSTS: ReviewPost[] = [
  {
    slug: 'global-bestseller-lipstick-top-10',
    category: 'lip',
    title: '2026 글로벌 베스트셀러 립스틱 톱 10 — Sephora·Olive Young 통합 데이터',
    summary:
      'Sephora 미국, Olive Young 한국, 일본 LOFT의 2026년 1분기 매출 데이터를 통합해 글로벌 베스트셀러 립스틱 톱 10을 정리했습니다.',
    intro:
      '글로벌 립스틱 시장에서 가장 잘 팔리는 제품은 무엇일까요. Sephora 미국 분기 매출, Olive Young 한국 베스트셀러, 일본 LOFT 데이터를 통합한 결과 의외로 한국과 미국의 베스트셀러는 점점 비슷해지고 있습니다. 2026년 1분기 글로벌 통합 베스트셀러 립스틱 톱 10을 가격·특징·장단점과 함께 정리합니다.',
    products: [
      {
        rank: 1,
        brand: 'Rom&nd (한국)',
        name: 'Juicy Lasting Tint — "Bare Grape", "Figfig"',
        price: '약 12,000원 / $14',
        highlight: '쿨톤·웜톤 모두 어울리는 MLBB(My Lips But Better) 컬러 라인',
        pros: ['12시간 지속력', '비건 인증', '글로벌 매진 1위 컬러 보유'],
        cons: ['글로시 마무리라 매트 선호자에는 부적합'],
      },
      {
        rank: 2,
        brand: '라네즈 (한국)',
        name: 'Lip Sleeping Mask',
        price: '약 22,000원 / $24',
        highlight: '입술 케어 마스크 + 컬러의 결합 — 누적 1억 개 판매',
        pros: ['바이올렛/베리 컬러 다양', '밤사이 보습 효과', 'BTS V 추천 후 글로벌 매진'],
      },
      {
        rank: 3,
        brand: 'Peripera (한국)',
        name: 'Ink Mood Glowy Tint',
        price: '약 9,800원 / $11',
        highlight: '귀여운 패키지 + 끈적이지 않는 글로시 마무리',
        pros: ['Z세대 한정 컬러 다수', '빠른 발색', '저렴한 가성비'],
      },
      {
        rank: 4,
        brand: 'Charlotte Tilbury (영국)',
        name: 'Pillow Talk Matte',
        price: '약 50,000원 / $40',
        highlight: '글로벌 럭셔리 시장 매트 립스틱 1위 5년 연속',
        pros: ['모든 피부톤 어울리는 누드 핑크', '매트지만 건조하지 않음', '브랜드 명성'],
        cons: ['고가'],
      },
      {
        rank: 5,
        brand: 'MAC (미국)',
        name: 'Russian Red',
        price: '약 30,000원 / $24',
        highlight: '진한 클래식 레드의 정수 — 마돈나 시그니처',
        pros: ['진한 발색', '매트 마무리', '모든 피부톤 어울리는 클래식 레드'],
      },
      {
        rank: 6,
        brand: 'Dasique (한국)',
        name: 'Juicy Dewy Tint',
        price: '약 12,000원 / $13',
        highlight: '"Clean Girl" 미적 표준의 milky 컬러 라인',
        pros: ['옅고 부드러운 발색', '글로시 마무리', '귀여운 패키지'],
      },
      {
        rank: 7,
        brand: '어뮤즈 (한국)',
        name: 'Wave Tint',
        price: '약 14,000원 / $15',
        highlight: '한 자루로 입·뺨·아이 사용 가능한 멀티 스틱',
        pros: ['멀티 사용', '비건', '2026 글로벌 매진 라인'],
      },
      {
        rank: 8,
        brand: 'Pat McGrath Labs (미국)',
        name: 'Mattetrance Lipstick',
        price: '약 50,000원 / $40',
        highlight: '런웨이 메이크업 아티스트 시그니처 라인',
        pros: ['풍부한 컬러 라인', '진한 발색', '럭셔리 패키지'],
        cons: ['고가'],
      },
      {
        rank: 9,
        brand: 'NARS (미국)',
        name: 'Powermatte Lip Pigment',
        price: '약 35,000원 / $28',
        highlight: '리퀴드 매트 립스틱의 클래식',
        pros: ['12시간 지속력', '진한 색상', '매트 마무리'],
        cons: ['건조할 수 있음'],
      },
      {
        rank: 10,
        brand: 'Glossier (미국)',
        name: 'Generation G',
        price: '약 25,000원 / $20',
        highlight: '"립스틱 흔적" 효과의 자연스러운 룩',
        pros: ['미니멀 무드', '발림성 좋음', '저자극'],
      },
    ],
    outro: [
      '데이터의 핵심 시사점: (1) 글로벌 톱 10 중 한국 브랜드가 6개 — K-뷰티 영향력. (2) 가격대 11달러 ~ 50달러로 다양 — 럭셔리에서 미들레인지로 시장 분산. (3) 글로시(7개)가 매트(3개)를 압도하지만, 차세대 트렌드인 매트 컴백이 명확.',
      '구매 전 체크: (1) 본인 퍼스널 컬러에 맞는 컬러군 선택. (2) 매트·새틴·글로시 마무리 본인 선호 확인. (3) 입술이 건조한 사람은 글로시 또는 보습 효과 있는 마스크형 권장. (4) 가성비 우선이면 한국 미들레인지(1만~1.5만원)가 럭셔리 대비 효능 차이 미미.',
    ],
    date: '2026-04-30',
    readMinutes: 7,
    tags: ['립스틱', '베스트셀러', '글로벌'],
    featured: true,
  },
  {
    slug: 'k-beauty-skincare-bestsellers-comparison',
    category: 'skincare',
    title: 'K-뷰티 스킨케어 베스트 10 — 효능·가격·민감성 비교',
    summary:
      'Olive Young, Sephora, 아마존에서 모두 베스트셀러인 K-뷰티 스킨케어 10개를 효능·가격·민감성 안전도로 비교 분석.',
    intro:
      'K-뷰티 스킨케어는 글로벌에서 매년 2,000개 이상 신제품이 출시되지만, 글로벌 매출 톱 10은 5년간 거의 변하지 않는 견고한 명성을 가진 라인으로 구성됩니다. Olive Young 한국, Sephora 미국, 아마존 K-뷰티 카테고리 데이터를 통합한 결과를 정리합니다.',
    products: [
      {
        rank: 1,
        brand: '코스알엑스',
        name: 'Advanced Snail 96 Mucin Power Essence',
        price: '약 18,000원 / $25',
        highlight: '5년 연속 글로벌 K-뷰티 1위, 누적 7,000만 개 판매',
        pros: ['스네일 뮤신 96% 농도', '재생·보습 효과', '저자극'],
        cons: ['비건 X (동물성 성분)'],
      },
      {
        rank: 2,
        brand: '메디큐브',
        name: 'Zero Pore Pad',
        price: '약 28,000원 / $32',
        highlight: '모공 케어 카테고리 글로벌 1위',
        pros: ['BHA + 시카 결합', '모공 깊이 케어', '간편한 패드 형태'],
      },
      {
        rank: 3,
        brand: '닥터지',
        name: 'Red Blemish Cica Cream',
        price: '약 22,000원 / $25',
        highlight: '시카 카테고리 한국 베스트 — 민감성 진정',
        pros: ['고농도 시카', '저자극', '트러블 진정'],
      },
      {
        rank: 4,
        brand: '비플레인',
        name: 'Cicamanu Cream',
        price: '약 16,000원 / $18',
        highlight: '신생 인디 브랜드의 글로벌 베스트셀러',
        pros: ['시카 + 마누카', '비건 인증', '가성비 우수'],
      },
      {
        rank: 5,
        brand: '토리든',
        name: 'DIVE-IN Low Molecule Hyaluronic Acid Serum',
        price: '약 21,000원 / $24',
        highlight: '다중 분자 히알루론산 — 깊이 보습',
        pros: ['5종 히알루론산 콤플렉스', '저자극', '글로시 글래스 스킨 효과'],
      },
      {
        rank: 6,
        brand: '메디힐',
        name: 'Teatree Care Solution Mask',
        price: '약 2,800원 / $3.50',
        highlight: '글로벌 시트마스크 베스트셀러',
        pros: ['트러블 진정', '저렴한 가격', '글로벌 30개국 판매'],
      },
      {
        rank: 7,
        brand: '스킨1004',
        name: '마다가스카르 시카 토너 미스트',
        price: '약 16,000원 / $18',
        highlight: '미스트 형태 시카 토너 — 외출 중 보충',
        pros: ['시카 + 판테놀', '저자극', '간편한 미스트 형태'],
      },
      {
        rank: 8,
        brand: '아누아',
        name: 'Heartleaf 77% Soothing Toner',
        price: '약 16,000원 / $18',
        highlight: '어성초 77% 함유 진정 토너',
        pros: ['항염', '저자극', '글로벌 매진 잦음'],
      },
      {
        rank: 9,
        brand: '미샤',
        name: 'Time Revolution The First Treatment Essence',
        price: '약 32,000원 / $35',
        highlight: '갈락토미세스 95% — SK-II 대안',
        pros: ['고농도 발효 성분', 'SK-II 1/3 가격', '안티에이징'],
      },
      {
        rank: 10,
        brand: '라운드랩',
        name: '자작나무 톤업 선크림',
        price: '약 20,000원 / $22',
        highlight: '한국 1위 자외선 차단제 5년 연속',
        pros: ['SPF 50+/PA++++', '톤업 효과', '저자극'],
      },
    ],
    outro: [
      '핵심 시사점: (1) 톱 10 평균 가격 ~22,000원 — 글로벌 럭셔리(70~150달러) 대비 1/4 ~ 1/5 수준. (2) "시카" 라인이 4개 — 민감성·진정 카테고리가 글로벌에서 K-뷰티 정체성. (3) 신생 인디 브랜드(비플레인, 토리든, 아누아)가 4개 — 5년 전 톱 10에 없던 새로운 흐름.',
      '구매 가이드: (1) 처음 K-뷰티 시도 → 1위 코스알엑스 + 6위 메디힐 마스크부터. (2) 민감성·트러블 → 3위 닥터지 + 7위 스킨1004. (3) 안티에이징 → 9위 미샤 + 5위 토리든. (4) 모공 케어 → 2위 메디큐브.',
    ],
    date: '2026-04-29',
    readMinutes: 7,
    tags: ['스킨케어', 'K-뷰티', '베스트셀러', '비교'],
  },
  {
    slug: 'vegan-cosmetics-best-brands-2026',
    category: 'vegan',
    title: '비건 화장품 글로벌 베스트 8 — 인증과 효능 비교',
    summary:
      'USDA Organic, Leaping Bunny, Vegan Society 인증을 모두 갖춘 글로벌 비건 화장품 8개 라인. 효능과 가격 균형을 비교했습니다.',
    intro:
      '비건 화장품 시장은 2026년 글로벌에서 가장 빠르게 성장하는 카테고리 중 하나로 연평균 16% 성장 중입니다. 그러나 "비건" 라벨은 인증이 다양해 신뢰도 차이가 큽니다. USDA Organic·Leaping Bunny·Vegan Society 3가지 인증을 모두 갖춘 글로벌 베스트 8개를 정리합니다.',
    products: [
      {
        rank: 1,
        brand: 'OSEA Malibu (미국)',
        name: 'Undaria Algae Body Oil',
        price: '$48',
        highlight: '향료 미함유 + 국립 습진 협회 인증',
        pros: ['하이포알러제닉', '민감성 안전', '약사 검증'],
      },
      {
        rank: 2,
        brand: 'Attitude (캐나다)',
        name: 'Oceanly Solid Cream',
        price: '$22',
        highlight: '92.9% 천연 성분 + 플라스틱 프리 패키지',
        pros: ['EWG 인증', '6개월 사용 가능', '환경 친화'],
      },
      {
        rank: 3,
        brand: 'Herbivore Botanicals (미국)',
        name: 'Bamboo Charcoal Cleansing Bar',
        price: '$12',
        highlight: '민감성 피부 친화 비건 비누',
        pros: ['100% 비건', '천연 성분', '저가격'],
      },
      {
        rank: 4,
        brand: 'REN Skincare (영국)',
        name: 'Evercalm Global Protection Day Cream',
        price: '$58',
        highlight: '오메가 3 + 7 + 칼렌듈라 함유',
        pros: ['고기능 안티에이징', '민감성 OK', '저자극'],
      },
      {
        rank: 5,
        brand: '비플레인 (한국)',
        name: 'Cicamanu Cream',
        price: '약 16,000원',
        highlight: '시카 + 마누카 비건 라인',
        pros: ['Vegan Society 인증', '저가격', 'K-뷰티 비건 베스트'],
      },
      {
        rank: 6,
        brand: '라카 (한국)',
        name: 'Vegan Lip Balm',
        price: '약 14,000원',
        highlight: 'BTS 사용 — 글로벌 매진',
        pros: ['100% 비건', '저자극', '컬러 다양'],
      },
      {
        rank: 7,
        brand: 'Tower 28 (미국)',
        name: 'BeachPlease Lip & Cheek Cream',
        price: '$22',
        highlight: '입·뺨 멀티 사용 비건 크림',
        pros: ['민감성 안전', '비건', '멀티 사용'],
      },
      {
        rank: 8,
        brand: 'Annmarie Skin Care (미국)',
        name: 'Wild Fruit Anti-Aging Serum',
        price: '$84',
        highlight: '안티에이징 비건 라인',
        pros: ['오가닉', '비건', '항산화 풍부'],
        cons: ['고가'],
      },
    ],
    outro: [
      '비건 화장품 선택 가이드: (1) 인증 마크 확인 — Leaping Bunny(동물실험 미실시), Vegan Society(동물성 원료 미사용), USDA Organic(95%+ 유기농). (2) 비건과 크루얼티 프리는 별개 — 둘 다 갖춘 제품이 안전. (3) "비건"이라고 자칭하는 무인증 제품 주의 — 인증이 신뢰의 핵심.',
      '가격 비교: 한국 비건 라인(라카, 비플레인) 미들레인지 1.4만~1.6만원, 미국 미들레인지(Tower 28, Herbivore) 12~22달러, 럭셔리(REN, Annmarie) 58~84달러. 효능 차이는 가격 차이만큼 크지는 않습니다.',
    ],
    date: '2026-04-28',
    readMinutes: 6,
    tags: ['비건', '인증', '글로벌', '비교'],
  },
  {
    slug: 'sensitive-skin-cosmetics-comparison',
    category: 'skincare',
    title: '민감성 피부에 가장 안전한 화장품 7가지',
    summary:
      '아토피·여드름·민감성 피부에도 자극이 거의 없는 글로벌 화장품 7개. 피부과 의사가 추천한 라인을 효능 순으로 정리.',
    intro:
      '민감성 피부는 글로벌 인구의 약 30%가 가진 가장 흔한 피부 타입입니다. 일반 화장품의 자극에 빠르게 반응해 발진·홍조·건조함을 보입니다. 글로벌 피부과 의사들이 가장 자주 추천하는 7개 안전 라인을 효능 순으로 정리합니다.',
    products: [
      {
        rank: 1,
        brand: 'CeraVe (미국)',
        name: 'Hydrating Facial Cleanser',
        price: '$16',
        highlight: '세라마이드 3종 + 히알루론산 — 피부과 의사 추천 1위',
        pros: ['저자극', '저가격', '글로벌 매니아'],
      },
      {
        rank: 2,
        brand: 'La Roche-Posay (프랑스)',
        name: 'Cicaplast Baume B5',
        price: '약 23,000원 / $20',
        highlight: '판테놀 5% + 마데카소사이드',
        pros: ['아기·임산부 사용 가능', '진정 효과', '글로벌 약국 베스트'],
      },
      {
        rank: 3,
        brand: 'Avène (프랑스)',
        name: 'Tolérance Control Soothing Cream',
        price: '약 35,000원 / $30',
        highlight: '온천수 베이스 + 최소 성분 (8가지)',
        pros: ['초민감성 안전', '저자극', '항염'],
      },
      {
        rank: 4,
        brand: '비플레인 (한국)',
        name: 'Cicamanu Cream',
        price: '약 16,000원 / $18',
        highlight: '시카 + 마누카 — 한국 민감성 라인 베스트',
        pros: ['저자극', '저가격', '비건'],
      },
      {
        rank: 5,
        brand: '닥터지 (한국)',
        name: 'Red Blemish Cica Cream',
        price: '약 22,000원 / $25',
        highlight: '한국 시카 라인 원조 — 18년 누적 검증',
        pros: ['고농도 시카', '저자극', '한국 피부과 추천'],
      },
      {
        rank: 6,
        brand: 'Curel (일본)',
        name: 'Intensive Moisture Care Cream',
        price: '약 25,000원 / $30',
        highlight: '세라마이드 + 일본 약사법 안전 등급',
        pros: ['저자극', '글로벌 약사 검증', '아토피 지원'],
      },
      {
        rank: 7,
        brand: 'Vanicream (미국)',
        name: 'Moisturizing Cream',
        price: '$15',
        highlight: '향료·염료·라놀린 등 알레르겐 제거',
        pros: ['최소 성분', '미국 피부과 의사 1위', '저가격'],
      },
    ],
    outro: [
      '민감성 피부 케어 원칙: (1) 적은 단계가 안전 — 클렌저 + 모이스처라이저 + 자외선 차단제 3단계만으로 출발. (2) 새 제품은 패치 테스트 — 귀 뒤나 팔 안쪽에 24시간. (3) 향료·에센셜 오일·알코올 함유 제품 피하기. (4) 시카·세라마이드·판테놀이 핵심 안전 성분.',
      '단계별 추천 콤보: 1단계(매우 민감) — Vanicream 또는 Avène만 사용. 2단계(중간) — La Roche-Posay 또는 닥터지 라인. 3단계(가벼운 민감) — 비플레인 또는 CeraVe. 처음에는 가장 단순한 라인부터 시작하고 점진적으로 추가하세요.',
    ],
    date: '2026-04-27',
    readMinutes: 6,
    tags: ['민감성', '안전', '비교'],
  },
  {
    slug: 'budget-cosmetics-under-30000-won',
    category: 'budget',
    title: '3만원 미만 가성비 화장품 톱 10 — 럭셔리 못지않은 효과',
    summary:
      '럭셔리 라인의 1/3 ~ 1/5 가격으로 비슷한 효과를 내는 글로벌 가성비 화장품 톱 10. 한국·일본·미국 미들레인지 베스트.',
    intro:
      '"럭셔리 화장품은 성분 좋고 효과 좋다"는 통념을 데이터가 깨고 있습니다. 글로벌 화장품 비교 기관들이 비행 검증한 결과, 미들레인지 가성비 라인이 럭셔리 대비 효능 차이가 1~5% 수준에 그치는 경우가 많습니다. 3만원 미만 가성비 톱 10을 정리합니다.',
    products: [
      {
        rank: 1,
        brand: '코스알엑스 (한국)',
        name: 'Snail 96 Mucin Essence',
        price: '약 18,000원',
        highlight: '글로벌 1위 K-뷰티 — 럭셔리 La Mer 대안',
        pros: ['글로벌 검증', '재생 효과', '저가격'],
      },
      {
        rank: 2,
        brand: 'The Ordinary (캐나다)',
        name: 'Niacinamide 10% + Zinc 1%',
        price: '약 9,000원 / $7',
        highlight: '10% 나이아신아마이드 — 럭셔리 비교 시 1/10 가격',
        pros: ['고농도 활성 성분', '저가격', '글로벌 매니아'],
      },
      {
        rank: 3,
        brand: '메디힐 (한국)',
        name: 'Teatree Mask 10ea',
        price: '약 15,000원',
        highlight: '시트마스크 글로벌 베스트 — 1장 1,500원',
        pros: ['저가격', '글로벌 30개국 판매', '진정 효과'],
      },
      {
        rank: 4,
        brand: 'Maybelline (미국)',
        name: 'Lash Sensational Mascara',
        price: '약 12,000원 / $10',
        highlight: '글로벌 마스카라 베스트 — 럭셔리 대안',
        pros: ['10층 브러쉬 디자인', '컬링 효과', '저가격'],
      },
      {
        rank: 5,
        brand: 'Peripera (한국)',
        name: 'Ink Mood Glowy Tint',
        price: '약 9,800원',
        highlight: 'Z세대 글로벌 매진 립',
        pros: ['귀여운 패키지', '12시간 지속', '저가격'],
      },
      {
        rank: 6,
        brand: 'Cezanne (일본)',
        name: 'Cheek & Lip Stick',
        price: '약 8,000원 / $7',
        highlight: '입·뺨 멀티 스틱 — 일본 1위',
        pros: ['멀티 사용', '저가격', '저자극'],
      },
      {
        rank: 7,
        brand: '닥터지 (한국)',
        name: '그린마일드업 시카 톤업 선크림',
        price: '약 22,000원',
        highlight: '한국 1위 자외선 차단제 — SPF 50+',
        pros: ['톤업 효과', '시카 함유', '저자극'],
      },
      {
        rank: 8,
        brand: 'Wet n Wild (미국)',
        name: 'MegaGlo Highlighting Powder',
        price: '약 10,000원 / $7',
        highlight: '럭셔리 BECCA 하이라이터 대안',
        pros: ['놀라운 발색', '저가격', '글로벌 추천'],
      },
      {
        rank: 9,
        brand: 'Heroine Make (일본)',
        name: 'Long & Curl Mascara',
        price: '약 18,000원 / $15',
        highlight: '워터프루프 마스카라 글로벌 베스트',
        pros: ['워터프루프', '컬링 효과', '안경 사용자 OK'],
      },
      {
        rank: 10,
        brand: '어퓨 (한국)',
        name: '샤프 비버 브로우',
        price: '약 6,500원',
        highlight: '눈썹 펜슬 한국 1위',
        pros: ['저가격', '디테일 펜슬', '결 살리기 쉬움'],
      },
    ],
    outro: [
      '핵심 시사점: (1) 가성비 톱 10 모두 글로벌 매진을 기록한 검증된 라인. (2) 한국 6개, 일본 2개, 미국 2개로 동아시아 미들레인지가 강세. (3) 럭셔리 대비 가격은 1/3~1/10이지만 효능은 비슷. (4) 신생 인디 브랜드보다 검증된 미들레인지가 안전.',
      '가성비 콤보 추천: (1) 풀 메이크업 — 코스알엑스 에센스(스킨케어) + 닥터지 자외선 차단(베이스) + 어퓨 눈썹(아이) + 페리페라(립) — 합계 5만원 안에 풀 루틴. (2) 미니멀 — Cezanne 멀티스틱 + Heroine Make 마스카라 + 코스알엑스 = 4만원에 가능.',
    ],
    date: '2026-04-26',
    readMinutes: 7,
    tags: ['가성비', '저가', '비교'],
  },
  {
    slug: 'anti-aging-cosmetics-comparison',
    category: 'skincare',
    title: '안티에이징 화장품 6가지 비교 — 펩타이드·레티놀·PDRN',
    summary:
      '잔주름·탄력·색소침착에 가장 효과적인 안티에이징 라인 6개. 핵심 성분(레티놀·펩타이드·PDRN·EGF)별로 비교 분석.',
    intro:
      '안티에이징 화장품은 글로벌 화장품 시장 매출의 35%를 차지하는 가장 큰 카테고리입니다. 그러나 같은 가격대라도 핵심 성분과 농도에 따라 효능 차이가 큽니다. 6개 글로벌 베스트 안티에이징 라인을 핵심 성분별로 비교합니다.',
    products: [
      {
        rank: 1,
        brand: 'SK-II (일본)',
        name: 'Facial Treatment Essence',
        price: '약 130,000원 / $99',
        highlight: 'PITERA 갈락토미세스 90%+ — 글로벌 럭셔리 베스트',
        pros: ['고농도 발효 성분', '글로벌 매니아', '안티에이징 검증'],
        cons: ['고가'],
      },
      {
        rank: 2,
        brand: '미샤 (한국)',
        name: 'Time Revolution The First Treatment Essence',
        price: '약 32,000원 / $35',
        highlight: '갈락토미세스 95% — SK-II 대안',
        pros: ['SK-II 1/4 가격', '비슷한 효능', '한국 베스트'],
      },
      {
        rank: 3,
        brand: 'Drunk Elephant (미국)',
        name: 'A-Passioni Retinol Cream',
        price: '약 90,000원 / $74',
        highlight: '레티놀 1% + 펩타이드 — 미국 럭셔리 베스트',
        pros: ['레티놀 효능 검증', '안티에이징', '미니멀 처방'],
        cons: ['고가', '레티놀 자극 가능'],
      },
      {
        rank: 4,
        brand: 'The Ordinary (캐나다)',
        name: 'Granactive Retinoid 5%',
        price: '약 18,000원 / $15',
        highlight: '레티놀 대안 그래낙티브 5% — 자극 적음',
        pros: ['레티놀보다 자극 적음', '저가격', '효능 검증'],
      },
      {
        rank: 5,
        brand: '메디큐브 (한국)',
        name: 'Exosome Shot 1000 Ampoule',
        price: '약 65,000원 / $75',
        highlight: '엑소좀 + 펩타이드 — 메디코스메틱 라인',
        pros: ['최신 메디코스메틱 성분', '재생 효과', '한국 인기'],
      },
      {
        rank: 6,
        brand: '동성제약 (한국)',
        name: 'PDRN Re-Plumping Booster',
        price: '약 45,000원 / $50',
        highlight: 'PDRN 화장품 라인 — 한국 메디코스메틱',
        pros: ['PDRN 함유', '한국 시술 후 케어 표준', '효능 검증'],
      },
    ],
    outro: [
      '성분별 효능 비교: (1) 레티놀 — 가장 강력한 검증된 안티에이징, 자극 가능. (2) 펩타이드 — 부드럽고 자극 적음, 효능은 약간 약함. (3) PDRN/엑소좀 — 최신 메디코스메틱, 재생 효과. (4) 갈락토미세스 — 발효 성분, 고농도일수록 효과적.',
      '단계별 추천: (1) 처음 안티에이징 → The Ordinary 그래낙티브(자극 적음) + 미샤 갈락토미세스. (2) 중급 → Drunk Elephant 레티놀(저녁) + 미샤 에센스(아침). (3) 고급 → SK-II + 메디큐브 엑소좀 + 동성제약 PDRN을 단계적으로 도입.',
      '주의: 임산부는 레티놀·PDRN 사용 금지. 민감성 피부는 그래낙티브 또는 펩타이드부터 시작. 어떤 라인도 8~12주 꾸준히 사용해야 효과 확인 가능.',
    ],
    date: '2026-04-25',
    readMinutes: 7,
    tags: ['안티에이징', '레티놀', '펩타이드', '비교'],
  },
  {
    slug: 'mens-cosmetics-essential-5',
    category: 'mens',
    title: '남성용 화장품 필수 5가지 — K-팝 아이돌도 사용하는 라인',
    summary:
      '처음 화장품에 도전하는 남성을 위한 필수 5가지. K-팝 아이돌·할리우드 배우들이 일상에서 사용하는 글로벌 베스트.',
    intro:
      '남성 화장품 시장은 2026년 글로벌에서 가장 빠르게 성장 중입니다(연평균 10.9%). 처음 시도하는 남성을 위한 필수 5가지 글로벌 베스트를 정리합니다. 모두 BTS, BLACKPINK 멤버, 할리우드 배우들이 일상에서 사용하는 검증된 제품입니다.',
    products: [
      {
        rank: 1,
        brand: '라네즈 (한국)',
        name: 'Lip Sleeping Mask',
        price: '약 22,000원 / $24',
        highlight: 'BTS V 추천 — 누적 1억 개 판매 글로벌 1위',
        pros: ['남녀 사용 가능', '입술 케어', '글로벌 매니아'],
      },
      {
        rank: 2,
        brand: '닥터지 (한국)',
        name: '그린마일드업 시카 톤업 선크림',
        price: '약 22,000원 / $25',
        highlight: '한국 1위 자외선 차단제 — 톤업 효과',
        pros: ['SPF 50+', '톤업 컬러 보정', '저자극'],
      },
      {
        rank: 3,
        brand: 'CeraVe (미국)',
        name: 'Hydrating Facial Cleanser',
        price: '약 18,000원 / $16',
        highlight: '글로벌 피부과 의사 1위 클렌저',
        pros: ['세라마이드 함유', '저자극', '저가격'],
      },
      {
        rank: 4,
        brand: '어퓨 (한국)',
        name: '샤프 비버 브로우 펜슬',
        price: '약 6,500원',
        highlight: '한국 눈썹 펜슬 1위 — 자연스러운 결',
        pros: ['디테일 펜슬', '저가격', '결 살리기 쉬움'],
      },
      {
        rank: 5,
        brand: '라카 (한국)',
        name: 'Vegan Lip Balm — Subtle Color',
        price: '약 14,000원',
        highlight: 'SEVENTEEN 사용 — 비건 컬러 립밤',
        pros: ['100% 비건', '자연스러운 컬러', '글로벌 매진'],
      },
    ],
    outro: [
      '5가지로 만드는 일상 루틴: (1) 아침 — CeraVe 클렌저 → 닥터지 자외선 차단 → (선택) 라카 립밤. (2) 저녁 — CeraVe 클렌저 → 라네즈 립 슬리핑 마스크 (잠자기 전). (3) 외출 — 어퓨 눈썹 정리. 5가지로 5분 안에 완성되는 미니멀 그루밍입니다.',
      '점진적 확장 (3개월 후): (1) 모이스처라이저 추가 — 한국 라카 또는 미국 Disco. (2) 톤업 BB크림 — 클리오 또는 일본 Shiseido Men. (3) 라이트 마스카라 — 한 번만. (4) 컬러 립 — 베리·코랄.',
      '흔한 오해 깨기: (1) "남자가 화장하는 건 부자연스럽다" — Z세대 남성 64%가 매일 사용. (2) "전용 라인이 필요하다" — 대부분 K-뷰티 라인은 젠더 뉴트럴. (3) "비싸다" — 5가지 합계 약 8만원, 6개월 사용 가능.',
    ],
    date: '2026-04-24',
    readMinutes: 5,
    tags: ['남성', '그루밍', '필수', '추천'],
  },
  {
    slug: 'eye-products-mascara-eyeliner-comparison',
    category: 'eye',
    title: '아이 메이크업 필수템 비교 — 마스카라·라이너·섀도우 톱 9',
    summary:
      '글로벌 아이 메이크업 베스트셀러 9개를 마스카라(3) + 라이너(3) + 섀도우(3)로 분류해 비교. 워터프루프부터 비건까지.',
    intro:
      '아이 메이크업은 인상의 50%를 결정합니다. 그러나 글로벌 시장에는 수천 종류의 마스카라·라이너·섀도우가 있어 선택이 어렵습니다. 글로벌 매출 데이터로 검증된 9개 베스트셀러를 카테고리별로 비교합니다.',
    products: [
      {
        rank: 1,
        brand: 'Heroine Make (일본)',
        name: 'Long & Curl Mascara',
        price: '약 18,000원 / $15',
        highlight: '워터프루프 마스카라 글로벌 1위',
        pros: ['완벽한 워터프루프', '컬링 효과', '안경 사용자 OK'],
      },
      {
        rank: 2,
        brand: '어퓨 (한국)',
        name: '빅퍼피 마스카라',
        price: '약 12,000원',
        highlight: '한국 마스카라 1위 — 5년 연속',
        pros: ['저가격', '컬링', 'Z세대 매니아'],
      },
      {
        rank: 3,
        brand: 'Maybelline (미국)',
        name: 'Lash Sensational Mascara',
        price: '약 12,000원 / $10',
        highlight: '글로벌 매니아 — 10층 브러쉬',
        pros: ['풍부한 볼륨', '저가격', '글로벌 어디서나'],
      },
      {
        rank: 4,
        brand: 'Kate (일본)',
        name: '디자이닝 펜슬 라이너',
        price: '약 13,000원 / $11',
        highlight: '일본 펜슬 라이너 1위',
        pros: ['그리기 쉬움', '저자극', '글로벌 베스트'],
      },
      {
        rank: 5,
        brand: '클리오 (한국)',
        name: '쇼킹 슬림 펜 라이너',
        price: '약 14,000원 / $12',
        highlight: '한국 라이너 1위 — 펠트팁 베스트',
        pros: ['선명한 라인', '워터프루프', '얇은 두께 컨트롤'],
      },
      {
        rank: 6,
        brand: 'Stila (미국)',
        name: 'Stay All Day Liquid Liner',
        price: '약 30,000원 / $24',
        highlight: '리퀴드 라이너 글로벌 베스트',
        pros: ['진한 발색', '12시간 지속', '미국 매니아'],
      },
      {
        rank: 7,
        brand: '클리오 (한국)',
        name: 'Pro Eye Palette',
        price: '약 30,000원 / $32',
        highlight: '16색 전문가용 팔레트 — 한국 1위',
        pros: ['풍부한 컬러', '글로벌 베스트', '발색 우수'],
      },
      {
        rank: 8,
        brand: 'Urban Decay (미국)',
        name: 'Naked Palette',
        price: '약 70,000원 / $54',
        highlight: '미국 누드 팔레트 클래식',
        pros: ['12색 누드 라인', '글로벌 매니아', '럭셔리 패키지'],
        cons: ['고가'],
      },
      {
        rank: 9,
        brand: '어뮤즈 (한국)',
        name: '듀이 텍스처 섀도우',
        price: '약 25,000원',
        highlight: '글로시 듀이 텍스처 — 2026 트렌드',
        pros: ['글로시 마무리', '비건', 'Z세대 인기'],
      },
    ],
    outro: [
      '카테고리별 추천 콤보: (1) 워터프루프 강력파 → Heroine Make + 클리오 라이너 + 클리오 팔레트. (2) 데일리 미니멀 → 어퓨 빅퍼피 + Kate 펜슬 + 어뮤즈 듀이. (3) 럭셔리 → Urban Decay 팔레트 + Stila 라이너 + 어떤 마스카라.',
      '구매 가이드: (1) 마스카라 — 안경 사용자라면 무조건 워터프루프 또는 튜빙. (2) 라이너 — 처음에는 펜슬, 익숙해지면 펠트팁. (3) 팔레트 — 누드 톤 8~12색만 있어도 거의 모든 룩 가능.',
      '평균 가격: 마스카라 1.2~1.8만원, 라이너 1.3~3만원, 섀도우 팔레트 2.5~7만원. 모든 카테고리에서 한국 미들레인지가 글로벌 럭셔리 대비 효능 비슷하면서 가격은 1/3 수준.',
    ],
    date: '2026-04-23',
    readMinutes: 7,
    tags: ['아이', '마스카라', '라이너', '섀도우'],
  },
  {
    slug: 'cushion-foundation-comparison-best-5',
    category: 'base',
    title: '쿠션 파운데이션 글로벌 톱 5 — 럭셔리부터 가성비까지',
    summary:
      'K-뷰티의 시그니처 발명품 쿠션 파운데이션. 한국·일본·럭셔리 라인 5개를 비교해 본인에 맞는 쿠션을 찾는 가이드.',
    intro:
      '쿠션 파운데이션은 2008년 한국에서 발명된 후 글로벌 표준이 됐습니다. 2026년 글로벌 매출 USD 3.9 billion 규모. 그러나 같은 쿠션이라도 마무리·지속력·가격이 천차만별입니다. 5개 대표 라인을 비교해 본인에 맞는 쿠션을 찾는 가이드를 정리합니다.',
    products: [
      {
        rank: 1,
        brand: '헤라 (한국)',
        name: 'Black Cushion',
        price: '약 65,000원 / $58',
        highlight: '한국 럭셔리 쿠션 1위 — 모공 케어',
        pros: ['우아한 글로시 마무리', 'SPF 34', '리필 가능'],
      },
      {
        rank: 2,
        brand: '라네즈 (한국)',
        name: 'Neo Cushion',
        price: '약 38,000원 / $42',
        highlight: '한국 미들레인지 1위 — 12시간 지속',
        pros: ['매트 마무리', '우수한 지속력', '리필 저렴'],
      },
      {
        rank: 3,
        brand: 'IOPE (한국)',
        name: 'Air Cushion XP',
        price: '약 48,000원 / $52',
        highlight: '쿠션의 발명 브랜드 — 클래식 글로시',
        pros: ['역사적 명성', '글로시 마무리', '리필 가능'],
      },
      {
        rank: 4,
        brand: 'Lancôme (프랑스)',
        name: 'Teint Idole Cushion',
        price: '약 95,000원 / $80',
        highlight: '럭셔리 쿠션 — 리필 가능',
        pros: ['우아한 패키지', '풍부한 컬러 라인', '럭셔리'],
        cons: ['고가'],
      },
      {
        rank: 5,
        brand: '어퓨 (한국)',
        name: '디스이즈 쿠션',
        price: '약 12,000원',
        highlight: '한국 가성비 쿠션 1위',
        pros: ['저가격', '저자극', '글로시 마무리'],
      },
    ],
    outro: [
      '쿠션 선택 가이드: (1) 마무리 — 글로시(헤라, 라네즈 글로우) vs 매트(라네즈 매트). 본인 피부 타입에 따라. (2) 컬러 — 본인 피부톤보다 0.5단계 밝은 톤이 자연스러운 톤업. (3) 가격 — 럭셔리(8만원+)는 패키지·향·브랜드 명성, 효능 차이는 미들레인지(3.5~6.5만원) 대비 미미.',
      '평균 사용 기간: 본체 + 리필 1번 = 5~6개월. 리필이 본체보다 30~50% 저렴해 장기적으로 미들레인지가 가장 경제적. 저가형(어퓨) → 미들(라네즈) → 럭셔리(헤라)의 단계적 업그레이드도 가능.',
      '관리 팁: (1) 스펀지는 한 달에 한 번 미지근한 비누물로 세척. (2) 개봉 후 6개월 이내 사용 — 산화된 쿠션은 들뜸 발생. (3) 직사광선·습기 피해 보관.',
    ],
    date: '2026-04-22',
    readMinutes: 6,
    tags: ['쿠션', '파운데이션', '비교'],
  },
  {
    slug: 'makeup-brushes-tools-essential',
    category: 'tools',
    title: '메이크업 도구 필수 5가지 — 브러쉬·스펀지·컬러 비교',
    summary:
      '아무리 좋은 화장품도 도구가 부족하면 효과가 반감됩니다. 글로벌 메이크업 아티스트 추천 필수 5가지 도구.',
    intro:
      '메이크업 결과의 약 30%는 도구가 결정합니다. 럭셔리 파운데이션을 잘못된 도구로 바르면 미들레인지보다 못한 결과가 나옵니다. 글로벌 메이크업 아티스트 50명이 추천한 필수 5가지 도구를 정리합니다.',
    products: [
      {
        rank: 1,
        brand: 'Beautyblender (미국)',
        name: 'Original Beauty Sponge',
        price: '약 25,000원 / $20',
        highlight: '메이크업 스펀지 글로벌 클래식',
        pros: ['균등한 베이스', '광범위 사용', '글로벌 매니아'],
        cons: ['3개월마다 교체'],
      },
      {
        rank: 2,
        brand: 'Real Techniques (미국)',
        name: 'Foundation Brush',
        price: '약 15,000원 / $12',
        highlight: '인조모 파운데이션 브러쉬 베스트',
        pros: ['균등한 도포', '저가격', '인조모 비건'],
      },
      {
        rank: 3,
        brand: 'Sigma Beauty (미국)',
        name: 'F84 Round Kabuki',
        price: '약 35,000원 / $30',
        highlight: '컨투어·하이라이터 브러쉬 베스트',
        pros: ['정확한 위치 컨트롤', '부드러운 모', '내구성'],
      },
      {
        rank: 4,
        brand: 'Shu Uemura (일본)',
        name: 'Eyelash Curler',
        price: '약 27,000원 / $22',
        highlight: '글로벌 속눈썹 컬러 1위 — 50년 클래식',
        pros: ['완벽한 컬링', '내구성', '아시아인 눈에 적합'],
      },
      {
        rank: 5,
        brand: 'Spectrum (영국)',
        name: '비건 브러쉬 세트 (10개)',
        price: '약 50,000원 / $40',
        highlight: '비건·크루얼티 프리 풀 세트',
        pros: ['10개 풀 세트', '비건', '저가격 풀 키트'],
      },
    ],
    outro: [
      '도구별 사용 가이드: (1) 베이스 → 뷰티블렌더(글로시) 또는 Real Techniques(매트). (2) 컨투어/블러쉬 → Sigma F84(정밀) 또는 둥근 파우더 브러쉬. (3) 아이섀도우 → 작은 디테일 브러쉬 + 큰 블렌딩 브러쉬 2개. (4) 속눈썹 → Shu Uemura 컬러는 평생.',
      '관리: (1) 브러쉬 주 1회 세척 — 박테리아 200배 차이. (2) 스펀지 주 2회 세척 — 가장 빠르게 박테리아 번식. (3) 마이크로파 60초 살균 가능(젖은 상태).',
      '교체 주기: (1) 뷰티블렌더 — 3개월. (2) 인조모 브러쉬 — 6개월~1년. (3) 천연모 브러쉬 — 1~2년. (4) 속눈썹 컬러 — 모가 빠지면 즉시 교체(눈에 위험).',
      '스타터 키트: 1번(뷰티블렌더) + 2번(베이스 브러쉬) + 4번(속눈썹 컬러) = 약 7만원으로 풀 메이크업 가능. 익숙해지면 점진적으로 5번 비건 세트로 업그레이드.',
    ],
    date: '2026-04-21',
    readMinutes: 6,
    tags: ['도구', '브러쉬', '필수'],
  },
]

export function getReviewBySlug(slug: string): ReviewPost | undefined {
  return REVIEW_POSTS.find((p) => p.slug === slug)
}

export function getReviewsByCategory(category?: string): ReviewPost[] {
  if (!category || category === 'all') return REVIEW_POSTS
  return REVIEW_POSTS.filter((p) => p.category === category)
}

export function getFeaturedReview(): ReviewPost | undefined {
  return REVIEW_POSTS.find((p) => p.featured)
}
