import type { ReviewPost } from './types'

// Hand-written English reviews — not machine translations. Same slugs as their
// Korean counterparts so the language toggle and hreflang map one-to-one. The
// per-product buy buttons build a Coupang search from brand + name, so brands
// are romanized (they still resolve on Coupang). Keep EN_REVIEW_SLUGS in sync.
export const REVIEW_POSTS_EN: ReviewPost[] = [
  {
    slug: 'global-bestseller-lipstick-top-10',
    category: 'lip',
    title: '2026 Global Bestselling Lipsticks: Top 10 (Sephora + Olive Young Data)',
    summary:
      'We merged Q1 2026 sales data from Sephora US, Olive Young Korea, and LOFT Japan into one global bestseller ranking of the top 10 lipsticks.',
    intro:
      'Which lipsticks actually sell best worldwide? Merging Sephora US quarterly sales, Olive Young Korea bestsellers, and Japan’s LOFT data, one thing stands out — the Korean and American bestseller lists keep converging. Here is the combined global top 10 for Q1 2026, with prices, strengths, and trade-offs.',
    products: [
      {
        rank: 1,
        brand: 'rom&nd (Korea)',
        name: 'Juicy Lasting Tint — "Bare Grape", "Figfig"',
        price: '$14 / ~₩12,000',
        highlight: 'An MLBB (My Lips But Better) line that flatters cool and warm tones alike',
        pros: ['12-hour wear', 'Vegan-certified', 'Holds the #1 globally sold-out shade'],
        cons: ['Glossy finish — not for matte lovers'],
      },
      {
        rank: 2,
        brand: 'Laneige (Korea)',
        name: 'Lip Sleeping Mask',
        price: '$24 / ~₩22,000',
        highlight: 'A lip-care mask plus color — over 100 million units sold',
        pros: ['Wide violet/berry range', 'Overnight moisture', 'Sold out globally after BTS V’s pick'],
      },
      {
        rank: 3,
        brand: 'peripera (Korea)',
        name: 'Ink Mood Glowy Tint',
        price: '$11 / ~₩9,800',
        highlight: 'Cute packaging with a non-sticky glossy finish',
        pros: ['Many Gen-Z limited shades', 'Fast payoff', 'Excellent value'],
      },
      {
        rank: 4,
        brand: 'Charlotte Tilbury (UK)',
        name: 'Pillow Talk Matte',
        price: '$40 / ~₩50,000',
        highlight: 'The global luxury matte #1 five years running',
        pros: ['Universally flattering nude-pink', 'Matte but not drying', 'Brand prestige'],
        cons: ['Pricey'],
      },
      {
        rank: 5,
        brand: 'MAC (US)',
        name: 'Russian Red',
        price: '$24 / ~₩30,000',
        highlight: 'The essence of a deep classic red — Madonna’s signature',
        pros: ['Rich payoff', 'Matte finish', 'A classic red for every skin tone'],
      },
      {
        rank: 6,
        brand: 'dasique (Korea)',
        name: 'Juicy Dewy Tint',
        price: '$13 / ~₩12,000',
        highlight: 'Milky shades for the "clean girl" aesthetic',
        pros: ['Soft sheer payoff', 'Glossy finish', 'Cute packaging'],
      },
      {
        rank: 7,
        brand: 'AMUSE (Korea)',
        name: 'Wave Tint',
        price: '$15 / ~₩14,000',
        highlight: 'A multi-stick for lips, cheeks, and eyes in one',
        pros: ['Multi-use', 'Vegan', 'A 2026 global sell-out'],
      },
      {
        rank: 8,
        brand: 'Pat McGrath Labs (US)',
        name: 'Mattetrance Lipstick',
        price: '$40 / ~₩50,000',
        highlight: 'The runway artist’s signature line',
        pros: ['Rich shade range', 'Bold payoff', 'Luxe packaging'],
        cons: ['Pricey'],
      },
      {
        rank: 9,
        brand: 'NARS (US)',
        name: 'Powermatte Lip Pigment',
        price: '$28 / ~₩35,000',
        highlight: 'The liquid-matte classic',
        pros: ['12-hour wear', 'Bold color', 'Matte finish'],
        cons: ['Can feel drying'],
      },
      {
        rank: 10,
        brand: 'Glossier (US)',
        name: 'Generation G',
        price: '$20 / ~₩25,000',
        highlight: 'The "just-blotted lipstick" natural look',
        pros: ['Minimal mood', 'Easy to apply', 'Low irritation'],
      },
    ],
    outro: [
      'What the data says: (1) Six of the global top 10 are Korean brands — a measure of K-beauty’s reach. (2) Prices span $11 to $40 as the market spreads from luxury into the mid-range. (3) Glossy finishes (7) outnumber matte (3), but the next wave — a matte comeback — is already clear.',
      'Before you buy: (1) Pick a color family that suits your personal color. (2) Decide your finish — matte, satin, or glossy. (3) If your lips run dry, lean glossy or a mask-type balm. (4) On a budget, Korean mid-range ($10–15) gives up little to luxury on performance.',
      '> TOOL: Not sure which shade family is yours? | /en/tools/makeup-mbti/ | Free makeup MBTI · 12 questions · no signup · each of the 16 types comes with its own lip shade shortlist',
      '> KEY: Final verdict — rom&nd Juicy Lasting Tint (#1) best balances value, payoff, and wear. For luxury, Charlotte Tilbury Pillow Talk Matte (#4); for a classic red, MAC Russian Red (#5).',
    ],
    date: '2026-04-30',
    readMinutes: 7,
    tags: ['Lipstick', 'Bestseller', 'Global'],
    featured: true,
  },
  {
    slug: 'k-beauty-skincare-bestsellers-comparison',
    category: 'skincare',
    title: 'K-Beauty Skincare Top 10: Efficacy, Price & Sensitive-Skin Fit',
    summary:
      'The combined Olive Young, Amazon, and Sephora bestseller list of K-beauty skincare — toners, serums, creams, and sunscreens compared on efficacy, price, and sensitivity fit.',
    intro:
      'K-beauty skincare has become the global benchmark. Here is the combined global bestseller top 10, compared on efficacy, price, and how well each suits sensitive skin.',
    products: [
      {
        rank: 1,
        brand: 'Anua (Korea)',
        name: 'Heartleaf 77% Soothing Toner',
        price: '$22 / ~₩21,000',
        highlight: 'A 77% heartleaf calming toner — the global cumulative #1',
        pros: ['Calms sensitivity', 'Low irritation', 'Global bestseller'],
      },
      {
        rank: 2,
        brand: 'Torriden (Korea)',
        name: 'Dynamic Cushion Toner',
        price: '$19 / ~₩18,000',
        highlight: 'A hyaluronic-acid hydrating toner',
        pros: ['Deep hydration', 'Non-sticky', 'Great value'],
      },
      {
        rank: 3,
        brand: 'Round Lab (Korea)',
        name: '1025 Dokdo Toner',
        price: '$20 / ~₩19,000',
        highlight: 'A mildly acidic, gentle-exfoliating toner',
        pros: ['Daily exfoliation', 'Gentle feel', 'Large size'],
      },
      {
        rank: 4,
        brand: 'Dr.G (Korea)',
        name: 'Red Blemish Clear Soothing Cream',
        price: '$26 / ~₩25,000',
        highlight: 'A cica calming cream',
        pros: ['Calms sensitive, blemish-prone skin', 'Fast absorption', 'Dermatologist-recommended'],
      },
      {
        rank: 5,
        brand: 'COSRX (Korea)',
        name: 'Advanced Snail 96 Mucin Power Essence',
        price: '$25 / ~₩23,000',
        highlight: 'A 96% snail-mucin essence',
        pros: ['Strengthens the skin barrier', 'Hydrating', 'Global bestseller'],
      },
      {
        rank: 6,
        brand: 'Beplain (Korea)',
        name: 'Mung Bean Pore Clarifying Cleansing Foam',
        price: '$15 / ~₩14,000',
        highlight: 'A mildly acidic, pore-care cleanser',
        pros: ['Pore care', 'Gentle cleanse', 'Great value'],
      },
      {
        rank: 7,
        brand: 'Aestura (Korea)',
        name: 'Atobarrier 365 Cream',
        price: '$31 / ~₩30,000',
        highlight: 'A ceramide barrier cream',
        pros: ['Suits dry, sensitive skin', 'Barrier repair', 'Dermatologist-recommended'],
      },
      {
        rank: 8,
        brand: 'Mediheal (Korea)',
        name: 'Madecassoside Essence Mask',
        price: '$3 / ~₩2,500 (per sheet)',
        highlight: 'A cica calming sheet mask',
        pros: ['Daily calming', 'Inexpensive', 'The global #1 sheet mask'],
      },
      {
        rank: 9,
        brand: 'Sulwhasoo (Korea)',
        name: 'First Care Activating Serum',
        price: '$92 / ~₩90,000',
        highlight: 'An herbal anti-aging serum',
        pros: ['Luxury line', 'Anti-aging', 'Global prestige'],
        cons: ['Expensive'],
      },
      {
        rank: 10,
        brand: 'Be Ready (Korea)',
        name: 'Glow Deep Serum',
        price: '$18 / ~₩17,000',
        highlight: 'A vitamin glow serum',
        pros: ['Adds radiance', 'Great value', 'Daily use'],
      },
    ],
    outro: [
      'Buying guide: (1) Toner by skin type — oily/blemish-prone: Anua or Round Lab; dry: Torriden. (2) Serum by goal — calming: COSRX; anti-aging: Sulwhasoo; glow: Be Ready. (3) For sensitive skin, start with dermatologist lines (Dr.G, Aestura).',
      '> KEY: Final verdict — a stable starter trio is the Anua heartleaf toner + COSRX snail essence + Aestura Atobarrier cream. For luxury, the Sulwhasoo First Care Activating Serum.',
    ],
    date: '2026-04-29',
    readMinutes: 7,
    tags: ['Skincare', 'K-beauty', 'Bestseller'],
  },
  {
    slug: 'cushion-foundation-comparison-best-5',
    category: 'base',
    title: 'Global Top 5 Cushion Foundations: From Luxury to Budget',
    summary:
      'HERA, CLIO, espoir, Laneige, and IOPE — five global bestselling cushion foundations compared on coverage, wear, finish, and price.',
    intro:
      'The cushion compact is the base-makeup format K-beauty invented and the world adopted. Here are five global bestsellers compared on coverage, wear, finish, and price.',
    products: [
      {
        rank: 1,
        brand: 'HERA (Korea)',
        name: 'Black Cushion',
        price: '$48 / ~₩60,000',
        highlight: 'A semi-matte, long-wear cushion — the global bestseller nicknamed "the real Chanel"',
        pros: ['High coverage', '12-hour wear', 'Semi-matte finish'],
        cons: ['Pricey'],
      },
      {
        rank: 2,
        brand: 'CLIO (Korea)',
        name: 'Kill Cover Mesh Glow Cushion',
        price: '$30 / ~₩28,000',
        highlight: 'The face of the glow-cushion category — natural radiance',
        pros: ['Glow finish', 'Medium coverage', 'Great value'],
      },
      {
        rank: 3,
        brand: 'espoir (Korea)',
        name: 'Pro Tailor Be Glow Cushion',
        price: '$27 / ~₩25,000',
        highlight: 'The Be Glow cushion — balanced radiance and coverage',
        pros: ['Balanced glow and coverage', 'Daily-friendly', 'Great value'],
      },
      {
        rank: 4,
        brand: 'Laneige (Korea)',
        name: 'Neo Cushion Matte',
        price: '$35 / ~₩33,000',
        highlight: 'A global matte-cushion bestseller',
        pros: ['Matte finish', 'High wear', 'Globally popular'],
      },
      {
        rank: 5,
        brand: 'IOPE (Korea)',
        name: 'Air Cushion Cover XP',
        price: '$39 / ~₩38,000',
        highlight: 'The brand that invented the cushion',
        pros: ['Original cushion tech', 'High coverage', 'Semi-matte'],
      },
    ],
    outro: [
      'How to choose: (1) Matte → HERA Black Cushion (luxury), Laneige Neo Cushion Matte (value). (2) Glow → CLIO Mesh Glow, espoir Be Glow. (3) High coverage → HERA, IOPE. (4) Best value → CLIO, espoir.',
      '> KEY: Final verdict — for a value glow cushion, CLIO Kill Cover Mesh Glow; for luxury long-wear matte, HERA Black Cushion. Beginners: espoir Be Glow balances glow and coverage best.',
    ],
    date: '2026-04-22',
    readMinutes: 6,
    tags: ['Cushion', 'Base', 'Foundation'],
  },
]

export function getReviewBySlugEn(slug: string): ReviewPost | undefined {
  return REVIEW_POSTS_EN.find((p) => p.slug === slug)
}
