import './policy.css'

type Page = 'home' | 'analysis' | 'terms' | 'privacy' | 'refund'

interface TermsProps {
  onNavigate: (page: Page) => void
}

export default function Terms({ onNavigate }: TermsProps) {
  return (
    <div className="legal-page">
      <div className="legal-header">
        <button className="legal-back" onClick={() => onNavigate('home')}>
          <span className="material-symbols-outlined">arrow_back</span>
        </button>
        <h1>Terms of Service</h1>
      </div>
      <div className="legal-content">
        <p className="legal-date">Effective Date: March 6, 2026</p>

        <h2>1. Agreement to Terms</h2>
        <p>By accessing or using kisskin (<a href="https://kisskin.net" target="_blank" rel="noopener noreferrer">https://kisskin.net</a>), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

        <h2>2. Service Description</h2>
        <p>kisskin is an AI-powered makeup simulation and beauty recommendation service. When you submit a photo, our AI generates:</p>
        <ul>
          <li>9 personalized makeup style previews applied to your face</li>
          <li>Skin type and tone analysis</li>
          <li>Customized cosmetic product recommendations</li>
        </ul>
        <p>Results are generated using OpenAI's image generation and language models, delivered instantly in your browser.</p>

        <h2>3. Payment & Billing</h2>
        <ul>
          <li>Each analysis is a <strong>one-time purchase of $2.99 USD</strong>. There are no subscriptions, recurring charges, or hidden fees.</li>
          <li>Payment is securely processed by <strong>Polar</strong> (<a href="https://polar.sh" target="_blank" rel="noopener noreferrer">polar.sh</a>), a Merchant of Record. Polar handles all billing, tax calculation, and payment processing on our behalf.</li>
          <li>Accepted payment methods include credit/debit cards and other methods supported by Polar.</li>
          <li>By completing a purchase, you authorize Polar to charge your selected payment method.</li>
          <li>Your payment receipt and invoice are provided by Polar. For billing inquiries, you may contact Polar directly or reach us at <strong>support@kisskin.net</strong>.</li>
        </ul>

        <h2>4. Delivery of Service</h2>
        <ul>
          <li>Results are delivered <strong>immediately</strong> after payment, directly in your browser.</li>
          <li>No download, account creation, or email is required to receive results.</li>
          <li>Results are available only during your current browser session. Once you close the page, results cannot be recovered. We recommend using the <strong>Save</strong> or <strong>Share</strong> feature before leaving.</li>
        </ul>

        <h2>5. Refund Policy</h2>
        <p>Please see our dedicated <a className="legal-link" onClick={() => onNavigate('refund')}>Refund Policy</a> page for full details. In summary:</p>
        <ul>
          <li>Since results are delivered instantly as digital content, <strong>all sales are generally final</strong>.</li>
          <li>Full refunds are granted if the Service fails to deliver results due to a technical error on our side.</li>
          <li>Refund requests are processed through Polar.</li>
        </ul>

        <h2>6. User Eligibility & Responsibilities</h2>
        <ul>
          <li>You must be at least <strong>13 years old</strong> to use this Service. Users under 18 should have parental consent.</li>
          <li>You must only upload photos of yourself, or photos for which you have explicit consent from the person depicted.</li>
          <li>You agree not to use the Service to generate harmful, illegal, deceptive, or offensive content.</li>
          <li>You are responsible for ensuring your uploaded content does not violate any third-party rights.</li>
        </ul>

        <h2>7. Intellectual Property</h2>
        <ul>
          <li><strong>Your photos:</strong> You retain full ownership of photos you upload. We claim no rights over your original images.</li>
          <li><strong>AI-generated results:</strong> The makeup simulation images are generated by OpenAI's models. You are granted a personal, non-exclusive license to use, save, and share your results. Commercial use of results is permitted.</li>
          <li><strong>Our content:</strong> The kisskin brand, logo, website design, and all original content are owned by kisskin and protected by applicable intellectual property laws.</li>
        </ul>

        <h2>8. AI Disclaimer</h2>
        <ul>
          <li>AI-generated makeup simulations are <strong>artistic approximations</strong>, not guarantees of real-world appearance.</li>
          <li>Product recommendations are AI-generated suggestions based on your skin analysis. kisskin does not manufacture, sell, or endorse any recommended products.</li>
          <li>kisskin is not liable for any purchasing decisions you make based on AI recommendations.</li>
          <li>AI results may vary based on photo quality, lighting, angle, and other factors.</li>
        </ul>

        <h2>9. Limitation of Liability</h2>
        <p>The Service is provided <strong>"as is" and "as available"</strong> without warranties of any kind, express or implied. To the maximum extent permitted by applicable law:</p>
        <ul>
          <li>kisskin shall not be liable for any indirect, incidental, special, consequential, or punitive damages.</li>
          <li>Our total liability for any claim shall not exceed the amount you paid for the specific transaction giving rise to the claim.</li>
        </ul>

        <h2>10. Service Availability</h2>
        <ul>
          <li>We strive for 24/7 availability but do not guarantee uninterrupted service.</li>
          <li>We may temporarily suspend the Service for maintenance, updates, or circumstances beyond our control.</li>
          <li>We reserve the right to modify, suspend, or discontinue the Service at any time with reasonable notice.</li>
        </ul>

        <h2>11. Prohibited Uses</h2>
        <p>You may not:</p>
        <ul>
          <li>Reverse-engineer, decompile, or attempt to extract the source code of the Service.</li>
          <li>Use automated tools (bots, scrapers) to access the Service.</li>
          <li>Circumvent payment or abuse free trials or promotional offers.</li>
          <li>Upload content that is illegal, explicit, or violates others' rights.</li>
        </ul>

        <h2>12. Governing Law</h2>
        <p>These Terms are governed by and construed in accordance with applicable international commercial laws. Any disputes shall be resolved through good-faith negotiation first, then through arbitration if necessary.</p>

        <h2>13. Changes to Terms</h2>
        <p>We may update these Terms at any time. Material changes will be posted on this page with an updated effective date. Your continued use of the Service after changes constitutes acceptance.</p>

        <h2>14. Contact Us</h2>
        <p>For any questions about these Terms:</p>
        <ul>
          <li>Email: <strong>support@kisskin.net</strong></li>
          <li>Website: <a href="https://kisskin.net" target="_blank" rel="noopener noreferrer">https://kisskin.net</a></li>
        </ul>
      </div>
    </div>
  )
}
