import type { GuidePost } from './types'

// Hand-written English guides — not machine translations of the Korean posts.
// Same slugs as their Korean counterparts so the language toggle and hreflang
// map one-to-one. Keep EN_GUIDE_SLUGS (enSlugs.ts) in sync with this list.
export const GUIDE_POSTS_EN: GuidePost[] = [
  // ── English originals (no Korean twin — see enOnlySlugs.ts) ──────────────
  // Demand check (Google autocomplete): "personal color analysis" pairs with
  // korea / seoul / near me / free. People are searching for the *Korean* version
  // of this service. We are an actual Seoul-based site — that is an angle YouCam,
  // Sephora and the US colour-analysis blogs structurally cannot copy.
  {
    slug: 'personal-color-analysis-korea',
    category: 'color',
    title: 'Personal Color Analysis in Korea — What It Costs, What Actually Happens, and How to Get 80% of It Free',
    summary:
      'Seoul studios charge ₩100,000–180,000 and book out two months ahead. Here is exactly what happens in that room, whether it is worth flying for, and how to get most of the answer before you go.',
    body: [
      '> TLDR: A 1:1 session in Seoul runs roughly ₩100,000–180,000 (about $75–135) for 60–90 minutes | Popular studios book out 1–2 months ahead — reserve before you fly, not after you land | Arrive with a completely bare face: no foundation, no tinted SPF, no coloured lip balm, no coloured contacts | Most Korean studios use a 12-type system (4 seasons × warm-cool × bright-muted), and many now take a spectrophotometer reading first | The single most useful part — knowing whether you are warm or cool — you can get for free in a minute, before you book',
      'Search "personal color analysis" and Google finishes the phrase for you: *korea*, *seoul*, *near me*. That is not an accident. Colour analysis exists all over the world, but Korea turned it into an industry — and for a lot of people the trip to Seoul is half the appeal.',
      'We build K-beauty tools from Seoul, so this is the version of the guide we can actually write honestly: what the session costs, what happens inside the room, what it gets you, and what you can figure out for free before you ever book.',
      '## What it costs in Seoul (2026)',
      'Prices vary by studio and by how much of the consultant\'s attention you get. As of 2026 the typical range looks like this: a **1:1 private session runs about ₩100,000–180,000** (roughly $75–135) for 60–90 minutes. **Group sessions are cheaper** — around ₩80,000–120,000 per person for a pair, and ₩60,000–90,000 in a group of three or more, because you are splitting the consultant\'s time.',
      'At the top end, a comprehensive session with a master consultant — detailed written report, makeup consultation, sometimes a shopping guide — can run past ₩400,000. **English-speaking sessions** typically sit around ₩120,000–180,000, since fewer studios offer them.',
      '> KEY: The price difference is mostly consultant time and language, not accuracy. A ₩400,000 session is not four times more correct than a ₩100,000 one — you are buying a longer report and more hand-holding.',
      '## What actually happens in the room',
      'A standard 60–90 minute session goes roughly like this.',
      'It opens with a short interview — the colours you gravitate to, how you dress, what is bugging you (people often arrive with a specific complaint: "everything makes me look tired"). Then, in 2026, many Seoul studios take an **instrument reading first**: a spectrophotometer measures your skin\'s brightness, redness and yellowness as numbers, so the visual analysis starts from objective data rather than the consultant\'s first impression.',
      'Then comes the part everyone pictures — **draping**. The consultant lays coloured fabrics against your face under controlled lighting, one after another, watching what happens to your skin. The right drape makes skin look even and lifted; the wrong one drags shadows out from under your eyes and turns your face grey. It is genuinely visible once someone shows you, which is a large part of why people find the session convincing.',
      'Most Korean studios then place you in a **12-type system**: the four seasons (Spring, Summer, Autumn, Winter) split along warm/cool and bright/muted axes. It maps closely onto the Western 12-season framework, so a result you get in Seoul travels.',
      '## Rules that will save your appointment',
      '> WARN: Arrive with a **completely bare face**. No foundation, no BB cream, no tinted sunscreen, no coloured lip balm. If you wear coloured contacts, take them out and bring glasses or clear lenses. The consultant is reading your raw skin — anything on top of it corrupts the result, and a studio that proceeds anyway is not doing the job properly.',
      'Two more practical notes. **Book before you fly.** Popular studios are reserved 1–2 months out, and "I\'ll sort it when I land" is how people end up at whichever studio had a cancellation. And go **early in your trip** if you plan to shop — the result is far more useful when you still have days of shopping ahead of you than on the morning of your flight home.',
      '## Is it worth it?',
      'Honest answer: it depends on what you want out of it.',
      '**It is worth it if** you shop a lot and keep making expensive mistakes, if you have never been able to explain why some clothes "work", or if you want the experience itself — for many people the Seoul session is a genuinely fun part of the trip, and the draping moment is memorable.',
      '**It is not worth flying for** if you just want to know whether to buy the coral lipstick or the berry one. That question — warm or cool — is the single most useful output of the whole session, and it is also the part you can get for free in about a minute.',
      '> TOOL: Find your season free, in 1 minute | /en/tools/personal-color/ | Free personal color analysis · 6 questions · no signup · warm/cool through to the 4 seasons',
      '## How to get 80% of it before you book',
      'Do this first, and you will either save the money or walk into the session knowing what to ask.',
      '**1. Settle warm vs cool yourself.** Cross-check three tests rather than trusting one. Hold gold jewellery next to your face, then silver, and watch your *face* rather than the metal — the wrong one makes you look sallow or shadowed. Put a sheet of pure white paper beside your cheek in indirect daylight and see whether your skin reads yellow-golden or pink-blue. Try a coral lipstick and then a blue-pink one. When two of the three agree, trust it.',
      '**2. Ignore the vein test if it disagrees with the rest.** It is the most quoted test and the least reliable: skin thickness, melanin, lighting, even room temperature change how blue your veins look. A cold room can make a warm-toned person\'s veins read blue.',
      '**3. Write down what you already know.** Which colours get you compliments? Which top do you own that you never wear even though you like it? A good consultant will ask exactly this — arriving with the answers makes the session sharper.',
      '> VERDICT: If you are already coming to Seoul and you like the idea, book it — it is a good experience and the draping is convincing. If you are asking whether to fly here *for* it, do the free version first. Most people discover that "am I warm or cool" was the entire question, and that one costs nothing to answer.',
      'Sources — 2026 Seoul pricing, session structure, the spectrophotometer step and the 12-type system are cross-referenced from English-language Seoul colour-analysis guides and studio listings; the no-makeup rule and 1–2 month booking lead time are consistent across every studio we checked.',
    ],
    date: '2026-07-13',
    readMinutes: 8,
    tags: ['personal color analysis korea', 'personal color analysis seoul', 'color analysis cost', 'korean color analysis', 'personal color analysis free'],
    featured: true,
    ctaHook: 'Want to see the colours on your own face first?',
  },
  // Demand: "virtual makeup try on free / online free / app", "ai makeup generator /
  // ai makeup online free". Competitive head terms (YouCam, L'Oréal, Sephora own them),
  // so we do not compete on "we're the best" — we compete on being the only ones
  // willing to say what these tools cannot do. That is the honest angle, and it is
  // also the one that survives contact with a reader who has already been burned.
  {
    slug: 'virtual-makeup-try-on-free',
    category: 'basics',
    title: 'Virtual Makeup Try-On, Free — How AI Makeup Actually Works (and What It Still Cannot Do)',
    summary:
      'Filters, AR try-ons and AI generators are three different technologies with three different failure modes. Here is what each one is good for, why AI makeup sometimes changes your face, and how to get a result worth keeping.',
    body: [
      '> TLDR: Three different technologies get called "virtual makeup" — AR filters (live, brand-owned, sells you a SKU), AI image generation (a new photo, more dramatic, can drift), and photo editing (manual, slow) | AI generators can restyle hair colour and skin finish; AR filters cannot | The classic AI failure is identity drift — it hands you back a prettier stranger | Your photo decides the result: flat front lighting, bare face, no heavy filter, eyes to camera | Free almost always means limited — someone is paying for the compute, so ask what they take in return (usually your email, or a watermark)',
      'If you have ever tried a virtual makeup tool and thought "that is not my face", you are not imagining it. The term covers at least three different technologies, and they fail in completely different ways. Knowing which one you are using tells you what to expect — and what to blame when it goes wrong.',
      'We run an AI makeup tool ourselves, so this guide is written from the inside, including the parts that are inconvenient for us to admit.',
      '## The three things people call "virtual makeup"',
      '**1. AR filters (live try-on).** This is what you meet on Sephora, L\'Oréal or YouCam. Your camera tracks your face in real time and the software paints a lipstick shade onto your lips, matched to a real product you can add to a cart. It is fast, it is live, and shade accuracy is genuinely the point — these companies exist to sell you that exact SKU.',
      'Its limits are structural. It can only paint on the regions it tracks — lips, lids, cheeks. It cannot change your hair colour, it cannot change the finish of your skin, and it cannot show you a *look* in the way a photo can. It answers "what does this lipstick look like on me", not "what would I look like with this whole aesthetic".',
      '**2. AI image generation.** The tool takes your photo and generates a new image with makeup applied. Because it is generating pixels rather than overlaying them, it can do things AR cannot — change hair colour, change skin finish from matte to glass, restyle an entire look at once. It is also the only one of the three that can show you a complete aesthetic rather than one product.',
      'And it has one signature failure, which we will come back to: it can quietly change your face.',
      '**3. Manual photo editing.** Photoshop, Facetune, and the retouching apps. Total control, total effort. Fine if you are already skilled; irrelevant if you just want to know whether you would suit a bold lip.',
      '> KEY: Pick by the question you are asking. "Does this exact lipstick suit me?" → AR try-on, on the brand\'s own site. "What would I look like with this whole look — makeup, hair colour, finish?" → AI generation. "I need one perfect image" → manual editing.',
      '## The thing AI makeup gets wrong: identity drift',
      'Here is the honest part. When an AI model regenerates a photo, nothing forces it to keep your face. Ask for "glamorous makeup" and a poorly-constrained model will happily give you glamorous makeup on a slightly different person — a narrower jaw, bigger eyes, a straighter nose. The result looks great and feels wrong, because it is not you. This is the single most common complaint about AI beauty tools, and it is a real technical problem, not user error.',
      'There are two ways to fight it. **Masking** restricts the edit to specific regions (lips, lids, cheeks) and composites the original pixels back everywhere else, which makes identity drift structurally impossible — but it also means the model can never touch your hair. **Prompt-level face locking** lets the model regenerate the whole photo while instructing it, forcefully, to preserve identity, bone structure, eye shape and expression. That buys you hair colour and full-look changes, at the cost of needing constant tuning.',
      'Neither is free. Any tool that changes your hair colour is regenerating your face too, and is therefore taking on drift risk. If a tool promises whole-look transformation *and* perfect identity preservation with no caveats, be sceptical.',
      '> WARN: The test for any AI makeup result is not "is it pretty". It is: **put it side by side with the original and check whether it is still you.** A tool that only shows you the after image, never the before, is not making that easy by accident.',
      '## Your photo decides your result',
      'Most bad AI makeup results are bad photos. Five minutes of care here beats any amount of retrying.',
      '**Light your face flatly from the front.** A window on a cloudy day is ideal. Harsh side light carves shadows the model will read as facial structure, and backlighting hides the very skin it is supposed to be reading.',
      '**Go bare-faced.** The model adds makeup — it does not remove yours. Existing makeup stacks with the generated makeup, and the result is muddy.',
      '**Skip the beauty filter.** Photos that arrive pre-smoothed have already lost the pores and texture the model needs. Filtered input reliably produces plastic output.',
      '**Face the camera, eyes to lens.** Extreme angles and profile shots leave the model guessing at half your face — and guessing is exactly when it drifts.',
      '> TIP: Take three photos, not one. Slight differences in lighting and angle change the result more than most people expect, and it costs you thirty seconds.',
      '> TOOL: Try 9 K-beauty looks on your own selfie | /analysis/ | AI makeup · 9 looks with matching hair colour · before/after side by side · first try free, no card',
      '## What "free" actually means',
      'Every one of these tools costs real money to run — image generation burns GPU time per image, and someone is paying for it. So "free" is always free *of something*, and it is worth knowing what.',
      'Usually it is one of: a **watermark** on the output, a **limited number** of free generations, a **sign-up** so they can email you later, or **ads**. AR try-ons from beauty brands are the exception — those really are free, because the tool *is* the advertisement; its job is to put a product in your cart.',
      'None of this is sinister. But if a tool is unlimited, watermark-free, sign-up-free and ad-free, the honest question is what it is doing with your photos. Read what happens to your uploads. Any tool worth using tells you plainly, and deletes them.',
      '## What to expect, realistically',
      'Virtual makeup is very good at answering "would this direction suit me" and quite bad at replacing the mirror. It will tell you that a bold berry lip changes your face more than you expected, or that a cool ash hair colour drains you. Those are useful answers, and getting them for free beats buying the lipstick to find out.',
      'It will not tell you how the product wears at hour six, how it reacts with your skin, or whether the texture feels good. No amount of AI closes that gap.',
      '> VERDICT: Use AR try-on for a specific product, AI generation for a whole look. Feed it a bare-faced, flatly-lit, unfiltered photo. Then judge the output against your original photo, not against how pretty it is. If it is prettier but not you, the tool failed — no matter how good the image looks.',
    ],
    date: '2026-07-13',
    readMinutes: 8,
    tags: ['virtual makeup try on free', 'ai makeup generator', 'ai makeup online free', 'virtual makeup try on', 'ai makeup app'],
    featured: true,
    ctaHook: 'Want to see 9 K-beauty looks on your own face?',
  },
  {
    slug: '10-minute-daily-makeup-routine',
    category: 'basics',
    title: 'The Korean 10-Minute Everyday Makeup Routine',
    summary:
      'A realistic five-step routine that gives you a clean, put-together face before work or class — in about ten minutes flat.',
    body: [
      'A ten-minute face is not about rushing. It is about building a routine you will actually keep every single day. The five steps below are the minimal daily routine most makeup artists reach for, and once the order becomes muscle memory you will finish in closer to eight minutes.',
      '> TLDR: Five steps = skin prep (1.5 min) → base (2 min) → eyes (3 min) → brows (1 min) → blush + lip (2.5 min) | Doing the same order every day is the whole trick | A tinted SPF lets you thin out or skip foundation and save time',
      '> KEY: The order never changes — skin prep → base → eyes → brows → blush + lip. Ten minutes total.',
      'Step 1 — Skin prep (1 min 30 sec). After cleansing, go toner → a light moisturizer → SPF 30 or higher. Choose a tinted or tone-up sunscreen and it doubles as light coverage, so you can thin out or skip foundation in the next step and save real time.',
      'Step 2 — Base (2 min). Tap a cushion or BB cream on with the sponge, starting on the high points — cheekbones, forehead, the bridge of the nose — and melting the edges out with the warmth of your fingertips. Dab concealer only on dark circles and spots, then press it in; do not rub. If pores or texture show, press a little loose powder over just those areas.',
      'Step 3 — Eyes (3 min). Sweep a matte nude shadow across the whole lid, then tap a deeper brown into the outer third for quiet definition. Tightline by dotting a pencil between the lashes and softly joining the dots. One coat of mascara on curled lashes is plenty.',
      'Step 4 — Brows (1 min). Brows set the whole impression of a face. Use a pencil or brow mascara one shade lighter than your hair and fill only the gaps, following the natural growth. Resist drawing a heavier or blockier shape than you already have — natural is the goal.',
      'Step 5 — Blush + lip (2 min 30 sec). Sweep blush in a soft circle on the cheekbones, then lip balm followed by a lipstick or tint in the same color family. Keeping blush and lip in one family — coral, pink, or berry — is what makes a quick face look intentional instead of thrown together.',
      '> TOOL: Which 10-minute face suits you? | /en/tools/makeup-mbti/ | Free makeup MBTI · 12 questions · no signup · your type comes with its own lip, eye and base palette',
      'A few things worth prepping in advance: keep the five to seven items you use daily within arm’s reach; build a small duplicate kit for your bag so you can touch up on the go; and add one deeper treatment mask on the weekend. A short weekday routine pays off far more when your skin is in good shape underneath.',
      '> TIP: For the first week, run a timer and check yourself at each step. Within days it naturally drops under eight minutes — the constant is doing the steps in the same order every time.',
      'Small seasonal tweaks make a real difference too. In summer or humidity, set with a matte finish and a setting spray to stop slippage. In winter or dry air, keep a glowy base but reapply lip balm often. On high-pollution days, lengthen your evening cleanse — a double cleanse of five minutes or more — to clear what has settled into your pores. When you travel, carry the same line in mini sizes so your result stays consistent even when the environment changes.',
    ],
    date: '2026-04-30',
    readMinutes: 5,
    tags: ['Basics', 'Daily', 'Routine', 'Minimal'],
    featured: true,
    ctaHook: 'See this everyday routine on your own face with AI',
  },
  {
    slug: 'cushion-foundation-no-cakiness-5-steps',
    category: 'base',
    title: 'Cushion Foundation Without the Cake: A 5-Step Method',
    summary:
      'By afternoon the cushion lifts on your cheeks and pores start to show. Here is the five-step method that keeps it clean for six hours and more.',
    body: [
      'The cushion compact is one of K-beauty’s signature inventions, but used the wrong way it manages to look cakey, emphasize pores, and turn shiny all at once. “My cushion cakes up by the afternoon” is one of the most common questions Korean makeup artists hear. Here is the five-step fix.',
      'Step 1 — Wait five minutes after skincare. Your moisturizer and sunscreen need to absorb fully before the cushion goes on. Tap product onto skin that is still wet and the base film never sets, so it begins to lift and crack as the hours pass. The order is skincare → wait five minutes → cushion.',
      'Step 2 — Add a primer step. If pores stand out or you run oily, smooth a light makeup primer over those areas first to give the cushion an even bed. CLIO and Japan’s Canmake both make affordable, reliable options in the budget-to-mid range.',
      'Step 3 — Tap, then one slide. Pick up a moderate amount on the puff and press it on in order — cheeks → forehead → chin → nose. Going over the same spot again and again builds thickness and causes cakeyness, so limit each area to two or three presses. Then take a clean section of the puff and glide once to melt the edges in for an even finish.',
      'Step 4 — Dot concealer, then press. Apply concealer only on dark circles and blemishes, after the cushion. Never drag it — always tap it in with a fingertip or a concealer brush. Dragging shoves the cushion layer around, and that is exactly where the cakeyness starts.',
      'Step 5 — Finishing powder (do not skip). Press a little powder into just the T-zone and the tops of the cheeks and you will hold a clean, matte finish for six hours and more. If you do not want a matte mood, dust translucent powder very thinly — you keep the glow but absorb the oil.',
      'Maintaining the cushion itself matters as much as application. Wash the sponge once a month in lukewarm soapy water; replace it the moment the surface darkens or the smell changes; and use it up within six months of opening. An oxidized cushion will cake no matter how good your technique is.',
      '> WARN: Smear concealer over a cushion and you push the whole base layer around, and the cakeyness begins. Always press it in. Dragged concealer will not make it six hours.',
      'Skin-type tweaks change the result. Oily skin: cut the glow and use a matte cushion plus T-zone powder. Dry skin: a glow cushion plus a highlighter on the cheekbones, with powder only where pores show. Combination skin: matte T-zone, dewy cheeks. From your late thirties, drop one step thinner than usual so fine lines and pores are not emphasized. Seasonally, a matte tone in summer and a glow tone in winter feels most natural — keeping both within one cushion line is the efficient move.',
    ],
    date: '2026-04-27',
    readMinutes: 5,
    tags: ['Cushion', 'Foundation', 'Base', 'How-to'],
    ctaHook: 'Curious how a dewy K-beauty base looks on you? Try it with AI',
  },
  {
    slug: 'monolid-hooded-eye-makeup-techniques',
    category: 'eye',
    title: 'Monolid & Hooded Eye Makeup: Techniques That Actually Show',
    summary:
      'Most tutorials assume a visible crease. For monolids, partial lids, and hooded eyes, the rules are different — here is what works for each eye shape.',
    body: [
      'Almost every makeup tutorial is built around a visible crease. But roughly 30% of East Asians — over half a billion people worldwide — have monolids or partial lids, and hooded eyes, where lid skin covers part of the eye, are common across every ethnicity. Here is how to work with each eye shape instead of against it.',
      '## Monolid eyes',
      'A lid with no crease. The defining trait is that a normal-width liner all but disappears when your eyes are open. So draw a line 1.5 to 2 times thicker than usual, placed so a sliver still shows when you look straight ahead. Best looks: a clean thick line, or a small cat-eye with a slightly lifted tail.',
      'The key with monolids is using the lid space. The flat, generous lid takes graphic makeup beautifully — color blocking (one shade up top, another below), graphic liner, and glitter focal points all read well, so this is a shape that rewards experimentation.',
      '## Inner-double lids',
      'A lid with a partial crease near the inner eye — the in-between shape, common in Korea, Japan, and China. Lift the liner up a touch so the inner crease stays visible and you get a natural gradient. Angle the cat-eye tail up about 30 degrees to counter any downturn.',
      '## Hooded eyes',
      'A lid where extra skin drapes over part of the eye and hides your liner. The fix is the floating liner — drawing the line where it stays visible with the eye open. Avoid the classic trap of drawing a line with the eye closed that vanishes the moment you open it.',
      'How to apply on hooded eyes: (1) watch yourself slowly open and close your eyes in the mirror to see how far the hood covers; (2) draw the liner just above the edge of the hood; (3) lift the cat-eye tail strongly to offset the downturn; (4) emphasize only the upper lashes and keep the lower ones natural.',
      '## Larger, rounder eyes',
      'If your eyes already read big and defined, heavy liner can overwhelm them. Smudge a soft dark-brown shadow instead of a hard line, or skip liner entirely and let a couple of coats of mascara carry the look.',
      '## Asymmetrical eyes',
      'Almost everyone’s eyes are slightly uneven. Do not try to draw them identical — judge balance from a step back in the mirror. Go a touch thicker on the smaller eye and a touch thinner on the larger one, and they even out.',
      '> TIP: Flip a selfie horizontally and your asymmetry jumps out at once. We only ever see ourselves in a mirror-reversed reflection, so we assume we are symmetrical — the un-flipped photo is how others actually see you, which makes it the honest reference for balance.',
      'Eye shape changes with age. A crisp crease in your twenties can start to hood from the late thirties as the lid begins to droop. Keep drawing liner in your old spot and it will all hide when your eyes are open, so re-check the visible position once a year by slowly opening and closing your eyes in the mirror. For monolids and hooded eyes alike, skip the painted-on fake crease — working with your own eye shape looks the most natural, and global trends increasingly lean into individual identity rather than away from it.',
    ],
    date: '2026-04-22',
    readMinutes: 6,
    tags: ['Eye', 'Monolid', 'Hooded eye', 'How-to'],
    ctaHook: 'Wondering what eye looks suit your eyes? See it with AI',
  },
  {
    slug: 'natural-no-makeup-makeup',
    category: 'basics',
    title: 'Korean “No-Makeup” Makeup: A 6-Step Natural Look',
    summary:
      'The hardest look there is — reading as if you wear nothing while your features still look awake. A six-step guide to the global no-makeup makeup look.',
    body: [
      'No-makeup makeup is the hardest look there is. It has to read as if you are wearing nothing while your features still look awake and defined. Makeup artists routinely call it the most labor-intensive look of all — here it is in six steps.',
      'Step 1 — It starts with skincare. No-makeup makeup pays off most when your bare skin is in good shape. A sheet mask the night before, daily sunscreen, and enough sleep do the heavy lifting. Right before makeup, use a light moisturizer and give it five minutes to absorb.',
      'Step 2 — Tone-up sunscreen or a light BB cream. Instead of a full foundation, finger-blend a tone-up sunscreen or sheer BB cream to even your tone just slightly. The goal is color correction only — keep your real skin texture visible. Dr.G’s tone-up base and Tower 28’s SunnyDays are global favorites here.',
      'Step 3 — Spot conceal. Tap concealer only on dark circles and blemishes, and press it in. Never spread it across the whole face. Preserving your skin’s natural texture is the entire point of this look.',
      'Step 4 — Your lip color, plus one shade. Use a balm or tint one step deeper than your natural lip color for a “your-lips-but-better” finish. Anything too defined reads as makeup. AMUSE’s dewy tint and Glossier’s Generation G are good picks.',
      'Step 5 — Glow highlighter and a natural blush. A whisper of glow highlighter on the highest point of the cheekbones adds life through light. Sweep a very soft coral or pink blush in a circle on the cheeks for a believable flush. You are after “looks healthy,” not “wearing blush.”',
      'Step 6 — Mascara and brows only. One coat of mascara on curled lashes — never two. Fill brow gaps along the natural growth. Shadow and liner are skipped, or kept to an absolute minimum.',
      '## Five core principles',
      '(1) Base thin and even — thickness is what reads as makeup. (2) Keep color close to your own tone — one or two steps deeper at most. (3) Glow only where it falls naturally — the top of the cheekbones, the bridge of the nose. (4) Blush where a real flush sits — circled on the cheekbones. (5) Mascara once — no fake length.',
      '> TOOL: Find your makeup personality type | /en/tools/makeup-mbti/ | Free makeup MBTI · 12 questions · no signup · 16 types, each with its own lip, eye and base palette',
      '## The counterintuitive part',
      'No-makeup makeup usually takes about 30% longer than a full face. The control is finer and small differences swing the result. Once it is second nature, though, it is the most efficient everyday work look there is.',
      '> KEY: No-makeup makeup is not about how much you put on — it is about how invisibly you put it on. Base thickness is what gives makeup away, and color intensity is the ceiling.',
      'What the look means shifts by age. In your twenties, skin is at its best, so minimizing nearly every step still reads natural. From the late thirties, as fine lines and pigmentation begin, “well cared for” is a more realistic target than “wearing nothing” — tone-up base, a cheekbone highlight, and a natural blush become the core three. Past forty, no-makeup makeup becomes the most elegant look of all, but a satin or glow finish hides fine lines better than matte. K-beauty’s “glass skin” trend is essentially the evolved form of no-makeup makeup — same philosophy: keep your real texture, build the impression with light.',
    ],
    date: '2026-04-12',
    readMinutes: 6,
    tags: ['No-makeup', 'Natural', 'Basics', 'How-to'],
    ctaHook: 'See a natural, no-makeup look rendered on your face with AI',
  },
  {
    slug: 'lipstick-stay-all-day-7-tips',
    category: 'lip',
    title: 'How to Make Lipstick Last All Day: 7 Tested Tips',
    summary:
      'Through coffee, lunch, and a full day of talking — seven techniques makeup artists use to keep lipstick from disappearing.',
    body: [
      'Lipstick that vanishes after coffee, lunch, and a few conversations is the world’s most-searched makeup frustration. Here are the seven tricks artists actually use, ordered by how much they move the needle.',
      '> KEY: The highest-impact steps are #1 (exfoliate), #3 (blot), and #4 (powder set). Do just those three and your wear time more than doubles.',
      '1. Exfoliating is the starting line. No lipstick lays down evenly over flaky skin. Massage a soft toothbrush with a little warm water and honey in small circles for 30 seconds, or use a lip scrub twice a week. Exfoliate, let a balm absorb for five minutes, then apply — that is how color sets evenly.',
      '2. Line first. Define the lip with a liner and lightly fill it in; the lipstick color then anchors inside the line. Even after a meal the liner stays, so the shape does not fall apart. Match the liner to your lipstick’s color family so it reads natural.',
      '3. Blot after the first coat. Apply once, slip a tissue between your lips and gently press to absorb the surface oils, then apply a second coat. That second layer bonds directly to the lip and roughly doubles the wear.',
      '4. Set with a dusting of powder. After the second coat, lay one ply of tissue over your lips and tap a little face powder through it. The fine powder that passes through acts as a matte fixative on the lipstick surface, and the longevity jumps. Skip this if you want a glossy finish — it sets matte.',
      '5. Reach for matte first. Within the same brand, matte outlasts satin and gloss. If you want shine, set color with a matte lipstick first, then dab gloss onto just the center of the lips — the “combo” trick that keeps both the wear and the shine.',
      '6. Eat from the inside of your lips. Tuck your lips slightly inward when you drink or eat so the edges do not touch the cup or fork. A small habit, but it makes a big difference in how much color survives lunch.',
      '7. Carry a touch-up kit. No trick holds a full day perfectly. A mini lipstick and a small mirror let you refresh in a minute. When you do, blot first and reapply a thin layer for the most natural result.',
      'It helps to know how color families wear, too. Matte dark shades (blood wine, deep plum) last longest, matte nudes next, satin corals and pinks after that, and glossy formulas fade first. So for meetings and presentations where touch-ups are awkward, reach for matte dark or matte nude; for dates and everyday wear, satin or gloss is fine. If your lips run dry, the fix is not dropping gloss — it is using balm more often to protect the lips themselves.',
    ],
    date: '2026-04-29',
    readMinutes: 6,
    tags: ['Lipstick', 'Longevity', 'How-to'],
    ctaHook: 'Find the lip colors that suit you — see them on your face with AI',
  },
]

export function getGuideBySlugEn(slug: string): GuidePost | undefined {
  return GUIDE_POSTS_EN.find((p) => p.slug === slug)
}
