import type { MbtiCode } from '../makeup-mbti/types'
import type { ProductRec } from './types'

/**
 * 메이크업 MBTI 16유형별 추천 제품 카테고리.
 * 각 유형 3개 — 베이스/립/아이 중심. 유형의 시그니처 스타일에 맞춰 큐레이션.
 */
export const MBTI_RECOMMENDATIONS: Record<MbtiCode, ProductRec[]> = {
  INTJ: [
    {
      category: '아이섀도',
      title: '메탈릭 싱글 아이섀도 (건메탈/브론즈)',
      features: ['고발색 메탈릭 시머', '발림 좋은 크림 타입', '건메탈·브론즈·다크 카퍼'],
      brandExamples: ['MAC', 'NARS', '데이지크'],
      whyForType: 'INTJ의 "계산된 강렬함"을 한 번에 완성하는 시그니처 포인트. 싱글 아이섀도로 정확한 배치가 가능합니다.',
      searchKeywords: '메탈릭 싱글 아이섀도 건메탈 브론즈',
      icon: 'visibility',
    },
    {
      category: '립',
      title: 'MLBB 베이지 누드 립',
      features: ['내 입술 톤에 1~2톤 어두운 MLBB', '세미매트~벨벳 질감', '발색 일관된 타입'],
      brandExamples: ['맥', '롬앤', '3CE'],
      whyForType: '메탈릭 아이가 강한 INTJ의 룩에 균형을 잡아주는 절제된 누드. 한 번 정하면 오래 재구매하세요.',
      searchKeywords: 'MLBB 누드 립 베이지 세미매트',
      icon: 'favorite',
    },
    {
      category: '쿠션',
      title: '세미매트 미디엄 커버 쿠션',
      features: ['세미매트 피니시 (과한 글로우 X)', '미디엄 커버리지', '지속력 8시간+'],
      brandExamples: ['헤라', '설화수', '아이오페'],
      whyForType: 'INTJ의 정돈된 설계에 맞는 깔끔한 세미매트. 글로우가 강하면 메탈릭 아이가 묻힐 수 있습니다.',
      searchKeywords: '세미매트 쿠션 미디엄 커버',
      icon: 'palette',
    },
  ],

  INTP: [
    {
      category: '아이섀도 팔레트',
      title: '비관습 컬러 포함 팔레트 (바이올렛/모스 등)',
      features: ['6~9색 다양한 컬러 조합', '바이올렛·모스·테라코타 포함', '매트+시머 혼합'],
      brandExamples: ['어뮤즈', '데이지크', 'ColourPop'],
      whyForType: 'INTP의 실험 정신을 충족시키는 다채로운 팔레트. 언더라인·이너코너 실험에 최적입니다.',
      searchKeywords: '바이올렛 모스 테라코타 아이섀도 팔레트',
      icon: 'visibility',
    },
    {
      category: '립',
      title: '모카 브라운 · 다크 뉴트럴 립',
      features: ['웜 또는 뉴트럴 브라운', '매트~벨벳 질감', '90s 다크 노드 느낌'],
      brandExamples: ['롬앤', 'MAC', '3CE'],
      whyForType: '평범하지 않은 모카·다크 브라운이 INTP의 컨셉추얼한 취향을 표현합니다.',
      searchKeywords: '모카 브라운 다크 누드 립 매트',
      icon: 'favorite',
    },
    {
      category: '아이라이너',
      title: '컬러 젤 아이라이너 (블루/바이올렛)',
      features: ['발색 선명한 젤 타입', '블루·바이올렛·그린 컬러', '언더라인/이너 코너 배치용'],
      brandExamples: ['클리오', '카라', 'Stila'],
      whyForType: '블랙이 아닌 컬러 라이너로 예상 밖의 포인트를 만드는 것이 INTP의 시그니처입니다.',
      searchKeywords: '컬러 아이라이너 블루 바이올렛 젤',
      icon: 'edit',
    },
  ],

  ENTJ: [
    {
      category: '립',
      title: '클래식 레드 립스틱',
      features: ['정순 레드 (블루 언더 or 뉴트럴)', '매트 지속력 최고', '풀 커버 발색'],
      brandExamples: ['MAC', 'YSL', 'Dior'],
      whyForType: 'ENTJ의 "공간 장악" 본질을 완성하는 단 하나의 무기. 가격이 있어도 투자할 가치가 있습니다.',
      searchKeywords: '클래식 레드 립스틱 매트',
      icon: 'favorite',
    },
    {
      category: '쿠션',
      title: '매트 · 세미매트 고커버 쿠션',
      features: ['매트 피니시', '고커버리지', '진지한 인상 강화'],
      brandExamples: ['헤라', '설화수', '에스티로더'],
      whyForType: '글로우가 과하면 전문성 신호가 희석됩니다. ENTJ에겐 매트 쿠션이 정답.',
      searchKeywords: '매트 고커버 쿠션 파운데이션',
      icon: 'palette',
    },
    {
      category: '아이라이너',
      title: '블랙 리퀴드 아이라이너',
      features: ['샤프한 펜 타입', '지속력 12시간+', '눈매 또렷하게 잡아주는 블랙'],
      brandExamples: ['메이블린', '클리오', '카라'],
      whyForType: '블랙 리퀴드 라인 하나로 눈매에 즉각적인 파워풀을 만드는 ENTJ의 필수 아이템.',
      searchKeywords: '블랙 리퀴드 아이라이너 샤프',
      icon: 'edit',
    },
  ],

  ENTP: [
    {
      category: '아이섀도 팔레트',
      title: '실험적 다컬러 팔레트',
      features: ['12색 이상', '매트+시머+글리터 혼합', '트렌드 컬러 포함'],
      brandExamples: ['UD', 'Huda Beauty', '어뮤즈'],
      whyForType: 'ENTP의 월간 테마 변주를 전부 받아주는 다컬러 팔레트. 하나면 테스트 가능 조합이 수십 가지.',
      searchKeywords: '다컬러 아이섀도 팔레트 12색 트렌드',
      icon: 'visibility',
    },
    {
      category: '립',
      title: '번진 블러드 틴트 (오렌지/체리)',
      features: ['번짐 좋은 수분 틴트', '그런지 무드', '의도적으로 흐트러진 마무리'],
      brandExamples: ['페리페라', '롬앤', '어뮤즈'],
      whyForType: '그런지 메이크업의 핵심인 "완벽 부수기"에 가장 잘 맞는 번진 틴트입니다.',
      searchKeywords: '블러드 틴트 오렌지 체리 번짐',
      icon: 'favorite',
    },
    {
      category: '글리터 · 아이 글리터',
      title: '포인트 글리터 · 아이 쥬얼리',
      features: ['크림/젤 글리터', '한정판 컬러', '언더 아이/이너 코너용'],
      brandExamples: ['ColourPop', '어뮤즈', 'Stila'],
      whyForType: '매번 다른 실험을 하는 ENTP에게 글리터는 기분 따라 꺼내 쓸 수 있는 최고의 포인트.',
      searchKeywords: '크림 글리터 아이 쥬얼리 포인트',
      icon: 'auto_awesome',
    },
  ],

  INFJ: [
    {
      category: '블러셔',
      title: '블러 드레이핑용 크림 블러셔',
      features: ['크림 타입 (번짐 좋음)', '라벤더/소프트 모브/아이시 핑크', '볼→관자놀이 연결 가능'],
      brandExamples: ['롬앤', '3CE', 'Rare Beauty'],
      whyForType: 'INFJ의 시그니처 블러 드레이핑을 완성하는 핵심 제품. 크림 타입이 경계 없이 번집니다.',
      searchKeywords: '크림 블러셔 드레이핑 라벤더 모브',
      icon: 'spa',
    },
    {
      category: '립',
      title: '번진 틴트 (로즈/플럼)',
      features: ['시어 수분 틴트', '로즈/플럼/모브 컬러', '안에서 번진 듯한 마무리'],
      brandExamples: ['롬앤', '페리페라', '디어달리아'],
      whyForType: '경계가 번진 소프트 립이 INFJ의 몽환적 감성을 가장 섬세하게 전달합니다.',
      searchKeywords: '로즈 플럼 시어 틴트 블러드 립',
      icon: 'favorite',
    },
    {
      category: '쿠션',
      title: '클라우드 스킨 피니시 쿠션',
      features: ['세미매트 + 소프트 글로우', '가볍고 촉촉한 발림', '블러처리된 듯한 마감'],
      brandExamples: ['어뮤즈', '헤라', '아이오페'],
      whyForType: 'INFJ의 무드가 녹아드는 부드러운 피부 위에 블러쉬/립이 얹어질 때 가장 자연스럽습니다.',
      searchKeywords: '클라우드 스킨 쿠션 세미매트 글로우',
      icon: 'palette',
    },
  ],

  INFP: [
    {
      category: '글리터 · 쉬머',
      title: '파스텔 글리터 · 샴페인 시머',
      features: ['파스텔 라벤더/실버/샴페인', '고운 입자 아이 쥬얼리', '눈두덩 중앙 포인트용'],
      brandExamples: ['어뮤즈', 'Stila', 'ColourPop'],
      whyForType: 'INFP의 판타지 감성을 가장 잘 표현하는 반짝임. 동화 속 주인공 같은 눈매가 완성됩니다.',
      searchKeywords: '파스텔 글리터 샴페인 시머 아이',
      icon: 'auto_awesome',
    },
    {
      category: '립',
      title: '글로시 피치 코랄 립',
      features: ['글로시/윤기 나는 피니시', '피치/코랄/베이비 핑크', '동화 감성'],
      brandExamples: ['롬앤', 'Fenty', '어뮤즈'],
      whyForType: '글로시 피치가 INFP의 "봄날 오후 햇살" 같은 로맨틱 감성을 완성합니다.',
      searchKeywords: '글로시 피치 코랄 립 글로스',
      icon: 'favorite',
    },
    {
      category: '블러셔',
      title: '베이비 핑크 소프트 블러셔',
      features: ['연한 핑크/피치 베이스', '파우더/크림 혼합', '볼 중앙에 자연스럽게'],
      brandExamples: ['3CE', '롬앤', '에뛰드'],
      whyForType: '소프트 핑크 블러셔가 INFP의 로맨틱 판타지를 볼에도 연장시킵니다.',
      searchKeywords: '베이비 핑크 소프트 블러셔',
      icon: 'spa',
    },
  ],

  ENFJ: [
    {
      category: '립',
      title: '코랄 블러드 틴트',
      features: ['웜 코랄 기반 수분 틴트', '시어~세미매트 질감', '자연스러운 혈색감'],
      brandExamples: ['페리페라', '롬앤', '어뮤즈'],
      whyForType: '따뜻한 코랄이 ENFJ의 "주변 편안하게 만드는 온기"를 입술에 담습니다.',
      searchKeywords: '코랄 블러드 틴트 웜 혈색',
      icon: 'favorite',
    },
    {
      category: '쿠션',
      title: '글로우 내추럴 쿠션',
      features: ['촉촉한 글로우 피니시', '라이트 커버리지', '피부 결 보정'],
      brandExamples: ['아이오페', '헤라', '이니스프리'],
      whyForType: 'ENFJ의 따뜻한 인상을 완성하는 건강한 글로우 피부. 과하지 않은 촉촉함이 핵심.',
      searchKeywords: '글로우 쿠션 내추럴 촉촉',
      icon: 'palette',
    },
    {
      category: '블러셔',
      title: '피치 코랄 블러셔',
      features: ['웜 피치/살몬', '파우더 또는 크림', '볼 중앙에 은은하게'],
      brandExamples: ['클리오', 'NARS', '에뛰드'],
      whyForType: '피치 코랄이 ENFJ의 친근하고 따뜻한 분위기를 볼에 완성합니다.',
      searchKeywords: '피치 코랄 살몬 블러셔',
      icon: 'spa',
    },
  ],

  ENFP: [
    {
      category: '립 틴트 세트',
      title: '미니 립 세트 (다색상)',
      features: ['3~5가지 컬러 조합', '피치/플럼/모브/오렌지', '기분 따라 교체'],
      brandExamples: ['롬앤', '어뮤즈', '페리페라'],
      whyForType: 'ENFP의 일일 팔레트 컨셉에 최적화. 기분 따라 매일 다른 립을 시도할 수 있습니다.',
      searchKeywords: '립 틴트 미니 세트 다색상',
      icon: 'favorite',
    },
    {
      category: '아이섀도 팔레트',
      title: '컬러풀 16색 팔레트',
      features: ['12~16색 다양한 컬러', '매트+시머+글리터', '트렌디 컬러 포함'],
      brandExamples: ['UD', 'Huda Beauty', '어뮤즈'],
      whyForType: 'ENFP의 무한한 실험 욕구를 받아주는 최대 확장성의 팔레트입니다.',
      searchKeywords: '16색 아이섀도 팔레트 트렌디',
      icon: 'visibility',
    },
    {
      category: '블러셔',
      title: '멀티 컬러 블러셔 팔레트',
      features: ['3~5가지 컬러 블러셔', '피치/핑크/플럼/코랄', '크림/파우더 혼합'],
      brandExamples: ['3CE', 'MAC', '클리오'],
      whyForType: '립과 매치해서 매일 달라지는 블러셔 컬러 — ENFP의 자유로운 스타일링을 완성합니다.',
      searchKeywords: '멀티 블러셔 팔레트 다색',
      icon: 'spa',
    },
  ],

  ISTJ: [
    {
      category: '쿠션',
      title: '스테디셀러 내추럴 쿠션',
      features: ['10년 이상 브랜드', '내추럴 커버리지', '일관된 발색'],
      brandExamples: ['아이오페', '이니스프리', '아모레퍼시픽'],
      whyForType: 'ISTJ의 "검증된 루틴"에 완벽히 부합하는 스테디셀러. 한 번 만족하면 5년+ 재구매합니다.',
      searchKeywords: '스테디셀러 내추럴 쿠션 아이오페',
      icon: 'palette',
    },
    {
      category: '립',
      title: 'MLBB 로즈 틴트',
      features: ['"내 입술 같은 컬러"', '시어 질감', '어떤 옷에도 무난'],
      brandExamples: ['페리페라', '이니스프리', '에뛰드'],
      whyForType: '변덕 없이 오래 쓸 수 있는 정석 MLBB. ISTJ의 일관된 스타일과 완벽하게 맞습니다.',
      searchKeywords: 'MLBB 로즈 틴트 내 입술 같은',
      icon: 'favorite',
    },
    {
      category: '아이섀도',
      title: '내추럴 브라운 4색 팔레트',
      features: ['4~6색 내추럴 브라운', '매트 기반 (시머 1~2색)', '모든 상황 OK'],
      brandExamples: ['에뛰드', '이니스프리', 'MAC'],
      whyForType: '복잡함 없이 매일 쓸 수 있는 브라운 팔레트. ISTJ의 신뢰할 수 있는 일관성을 담습니다.',
      searchKeywords: '내추럴 브라운 4색 팔레트 베이직',
      icon: 'visibility',
    },
  ],

  ISFJ: [
    {
      category: '쿠션',
      title: '촉촉 클라우드 스킨 쿠션',
      features: ['촉촉한 글로우 피니시', '저자극 성분', '라이트 커버리지'],
      brandExamples: ['이니스프리', '어뮤즈', '이글리쉬'],
      whyForType: 'ISFJ의 "포근한 돌봄" 철학을 피부에 담는 촉촉한 클라우드 스킨.',
      searchKeywords: '촉촉 클라우드 스킨 쿠션 저자극',
      icon: 'palette',
    },
    {
      category: '립',
      title: '로즈 핑크 시어 틴트',
      features: ['연한 로즈 핑크', '시어 수분 질감', '친근한 혈색감'],
      brandExamples: ['롬앤', '페리페라', '이니스프리'],
      whyForType: '부드러운 로즈 핑크가 ISFJ의 포근한 이미지와 완벽하게 조화됩니다.',
      searchKeywords: '로즈 핑크 시어 틴트 연한',
      icon: 'favorite',
    },
    {
      category: '블러셔',
      title: '베이비 피치 파우더 블러셔',
      features: ['연한 피치', '파우더 타입 (가벼움)', '볼 중앙에 은은하게'],
      brandExamples: ['에뛰드', '클리오', '어뮤즈'],
      whyForType: '은은한 피치 블러셔가 ISFJ 특유의 부드러운 온기를 볼에 더합니다.',
      searchKeywords: '베이비 피치 파우더 블러셔',
      icon: 'spa',
    },
  ],

  ESTJ: [
    {
      category: '립',
      title: '블러드 레드 세미매트 립',
      features: ['딥 블러드 레드', '세미매트 지속력', '공식적 인상'],
      brandExamples: ['MAC', '롬앤', '헤라'],
      whyForType: 'ESTJ의 "공식 자리 정석"을 완성하는 블러드 레드. 신뢰감 있는 단정함이 시그니처.',
      searchKeywords: '블러드 레드 세미매트 립 공식',
      icon: 'favorite',
    },
    {
      category: '쿠션',
      title: '세미매트 고커버 쿠션',
      features: ['세미매트 피니시', '미디엄~고커버', '지속력 중시'],
      brandExamples: ['헤라', '설화수', '아이오페'],
      whyForType: 'ESTJ의 체계적 루틴에 맞는 안정적 커버리지. 매일 일관된 결과를 보장합니다.',
      searchKeywords: '세미매트 고커버 쿠션 지속력',
      icon: 'palette',
    },
    {
      category: '눈썹',
      title: '브라운 아이브로우 펜슬 + 파우더',
      features: ['2-in-1 펜슬+파우더', '내추럴 브라운', '단정하고 또렷한 눈썹'],
      brandExamples: ['클리오', '카라', 'Benefit'],
      whyForType: '또렷한 눈썹이 ESTJ의 단정한 인상 완성. 매일 정확히 같은 모양을 그릴 수 있어야 합니다.',
      searchKeywords: '아이브로우 펜슬 파우더 브라운',
      icon: 'edit',
    },
  ],

  ESFJ: [
    {
      category: '쿠션',
      title: 'K-pop 아이돌 핑크 글로우 쿠션',
      features: ['핑크 글로우 피니시', '촉촉+화사', 'SNS 사진에 예쁘게'],
      brandExamples: ['어뮤즈', '아이오페', '롬앤'],
      whyForType: 'ESFJ의 트렌디 K-pop 룩을 완성하는 화사한 글로우. 사진에도 잘 나옵니다.',
      searchKeywords: 'K-pop 핑크 글로우 쿠션 SNS',
      icon: 'palette',
    },
    {
      category: '립',
      title: '시어 로즈 글로스 틴트',
      features: ['시어 글로시', '로즈/피치 베이스', '통통한 입술 효과'],
      brandExamples: ['롬앤', '페리페라', '어뮤즈'],
      whyForType: '친근하면서도 예쁜 시어 로즈 틴트가 ESFJ의 멀티 TPO를 커버합니다.',
      searchKeywords: '시어 로즈 글로시 틴트 글로스',
      icon: 'favorite',
    },
    {
      category: '아이섀도 팔레트',
      title: '핑크 골드 데일리 팔레트',
      features: ['핑크/골드 계열', '시머 중심', '데일리 6색'],
      brandExamples: ['데이지크', '어뮤즈', '클리오'],
      whyForType: '핑크 골드 시머가 ESFJ의 무대성과 친근함을 동시에 전달합니다.',
      searchKeywords: '핑크 골드 아이섀도 팔레트 데일리',
      icon: 'visibility',
    },
  ],

  ISTP: [
    {
      category: '멀티 스틱',
      title: '립·볼·아이 3in1 멀티 스틱',
      features: ['한 제품 3역할', '스틱 타입 (휴대 편리)', '발림 바로 가능'],
      brandExamples: ['3CE', '디어달리아', 'Glossier'],
      whyForType: 'ISTP의 효율주의에 완벽히 맞는 멀티 제품. 3분 루틴의 핵심 아이템.',
      searchKeywords: '멀티 스틱 립 볼 아이 3in1',
      icon: 'auto_fix_high',
    },
    {
      category: '쿠션',
      title: '라이트 커버 BB 쿠션',
      features: ['자연스러운 라이트 커버', '빠른 발림', 'SPF 포함'],
      brandExamples: ['이니스프리', '아이오페', '에뛰드'],
      whyForType: '풀 메이크업이 부담스러운 ISTP에게 BB 쿠션 하나면 충분합니다.',
      searchKeywords: '라이트 커버 BB 쿠션 SPF',
      icon: 'palette',
    },
    {
      category: '립밤',
      title: '틴티드 립밤',
      features: ['립밤 + 컬러', '자연스러운 혈색', '수정 없이 종일 가능'],
      brandExamples: ['디어달리아', '롬앤', 'Laneige'],
      whyForType: '3분 루틴의 마무리. 립밤 하나로 케어+컬러 둘 다 해결됩니다.',
      searchKeywords: '틴티드 립밤 컬러 케어',
      icon: 'favorite',
    },
  ],

  ISFP: [
    {
      category: '립 틴트',
      title: '번진 체리 / 연한 플럼 틴트',
      features: ['번짐 좋은 수분 틴트', '체리/플럼/베리', '꾸안꾸 느낌'],
      brandExamples: ['롬앤', '페리페라', '어뮤즈'],
      whyForType: 'ISFP의 꾸안꾸 감성을 완성하는 번진 틴트. 힘을 빼도 감성은 살아남.',
      searchKeywords: '번진 체리 플럼 틴트 꾸안꾸',
      icon: 'favorite',
    },
    {
      category: '쿠션',
      title: '클라우드 스킨 저자극 쿠션',
      features: ['촉촉 클라우드 피니시', '비건/저자극 브랜드', '자연스러운 커버'],
      brandExamples: ['이니스프리', '어뮤즈', 'APLB'],
      whyForType: 'ISFP의 감성과 자연주의에 모두 맞는 비건/저자극 쿠션. 피부가 먼저 좋아보입니다.',
      searchKeywords: '클라우드 스킨 비건 저자극 쿠션',
      icon: 'palette',
    },
    {
      category: '마스카라',
      title: '내추럴 볼륨 마스카라',
      features: ['자연스러운 속눈썹', '번짐 방지', '라이트 볼륨'],
      brandExamples: ['클리오', '메이블린', '이니스프리'],
      whyForType: '과하지 않은 마스카라가 ISFP의 꾸안꾸를 마무리합니다.',
      searchKeywords: '내추럴 볼륨 마스카라 번짐 방지',
      icon: 'visibility',
    },
  ],

  ESTP: [
    {
      category: '아이섀도 팔레트',
      title: '스모키 다크 팔레트',
      features: ['블랙/차콜/다크 레드', '매트 기반', '강한 스모키 연출용'],
      brandExamples: ['UD', 'NARS', '어뮤즈'],
      whyForType: 'ESTP의 에너지를 눈매에 담는 스모키 팔레트. 강렬한 포인트가 핵심입니다.',
      searchKeywords: '스모키 다크 팔레트 블랙 차콜',
      icon: 'visibility',
    },
    {
      category: '립',
      title: '매트 레드 / 딥 플럼 립',
      features: ['매트 풀 커버', '레드/플럼/딥 베리', '지속력 최상'],
      brandExamples: ['MAC', '롬앤', 'YSL'],
      whyForType: '매트 레드가 ESTP의 풀메이크업 스릴을 완성합니다.',
      searchKeywords: '매트 레드 딥 플럼 립 풀커버',
      icon: 'favorite',
    },
    {
      category: '쿠션',
      title: '풀 커버 매트 파운데이션',
      features: ['풀 커버리지', '매트 지속력 최강', '밀착형'],
      brandExamples: ['MAC', '에스티로더', '메이블린'],
      whyForType: '강한 스모키/립을 받쳐줄 풀 커버 매트. 밤까지 무너지지 않아야 합니다.',
      searchKeywords: '풀 커버 매트 파운데이션 지속력',
      icon: 'palette',
    },
  ],

  ESFP: [
    {
      category: '글리터 · 하이라이터',
      title: '메탈릭 글리터 하이라이터',
      features: ['강한 메탈릭 펄', '샴페인/골드/핑크', '광대/콧등/이너코너'],
      brandExamples: ['Fenty', 'Stila', '어뮤즈'],
      whyForType: 'ESFP의 "스포트라이트" 본능을 완성하는 반짝임. 빛을 끌어당기는 핵심 아이템.',
      searchKeywords: '메탈릭 글리터 하이라이터 샴페인 골드',
      icon: 'auto_awesome',
    },
    {
      category: '립',
      title: '글로시 체리 · 플럼핑 립글로스',
      features: ['글로시/반짝이는 피니시', '통통한 플럼핑 효과', '체리/핑크 컬러'],
      brandExamples: ['Fenty', '롬앤', '어뮤즈'],
      whyForType: '글로시한 반짝임이 ESFP의 파티 느낌을 완성합니다.',
      searchKeywords: '글로시 체리 플럼핑 립글로스',
      icon: 'favorite',
    },
    {
      category: '아이섀도 팔레트',
      title: '샴페인 메탈릭 + 핑크 팔레트',
      features: ['시머+글리터 중심', '샴페인/로즈/피치', '무대성 강조'],
      brandExamples: ['데이지크', 'Huda Beauty', '어뮤즈'],
      whyForType: '샴페인 메탈릭이 ESFP의 화려한 사교 에너지를 눈매에 담습니다.',
      searchKeywords: '샴페인 메탈릭 핑크 아이섀도 팔레트',
      icon: 'visibility',
    },
  ],
}
