import type { ProductPost } from './types'

// 메이크업 제품 (Makeup Products) — English feed.
// Auto-translated from items.ts by scripts/gen-products.mjs (same slug so the
// language toggle and hreflang map one-to-one). Newest on top.
export const PRODUCT_ITEMS_EN: ProductPost[] = [
  {
    slug: 'anua-heartleaf-silky-moisture-sun-cream',
    category: 'skincare',
    brand: 'Anua',
    name: 'Heartleaf Silky Moisture Sun Cream',
    title: 'Anua Heartleaf Silky Moisture Sun Cream: Hydrating & Calming Sun Care Without Stickiness',
    summary:
      'A comfortable sun cream for all skin types, offering skin soothing with Heartleaf extract and a silky, moist finish. It absorbs freshly without a white cast, making it ideal for use before makeup.',
    highlights: ['Hydrating, No White Cast', 'Heartleaf Calming Care', 'Fresh Finish', 'Prevents Makeup Slippage'],
    details: [
      'Contains 30% Heartleaf extract to help soothe and protect skin, while Panthenol prevents moisture loss, keeping skin hydrated.',
      'Provides powerful SPF50+ PA++++ UV protection, shielding skin completely from UVA and UVB rays.',
      'Light, moist lotion texture absorbs quickly without a white cast or stickiness, leaving a fresh finish.',
      'Helps control excess sebum, maintaining a clean base for makeup for a long time without slippage.',
    ],
    image: '/products/anua-heartleaf-silky-moisture-sun-cream.webp',
    coupangQuery: '아누아 어성초 실키 모이스처 선크림',
    globalQuery: 'Anua Heartleaf Silky Moisture Sun Cream',
    clio: false,
    clioCategory: 'main',
    date: '2026-07-10',
    tags: ['sunscreen', 'heartleaf', 'calming', 'hydration', 'dailysunscreen', 'sensitiveskin'],
  },
  {
    slug: 'charlotte-tilbury-pillow-talk-lip-cheek-glow-colour-of-dreams',
    category: 'trend',
    brand: 'Charlotte Tilbury',
    name: 'Pillow Talk Lip & Cheek Glow (Color of Dreams)',
    title: 'Charlotte Tilbury Pillow Talk Lip & Cheek Glow: Vibrant Rosebud Pink',
    summary:
      'A multi-use cream blush and lip tint from Charlotte Tilbury that brings vitality to lips and cheeks. A popular item from the \'Pillow Talk\' collection, it applies with a chiffon-like lightness for a natural flush.',
    highlights: ['Chiffon-light texture', 'Moist and radiant finish', 'Vibrant rosebud pink', 'Contains raspberry extract'],
    details: [
      'The chiffon-light cream formula glides smoothly onto skin and blends easily without caking.',
      'Formulated with raspberry leaf stem cell extract and Vitamin E to provide moisture to lips and cheeks, promoting healthy, radiant skin.',
      'The warm rosebud pink shade, \'Color of Dreams,\' blends naturally like your own flush, adding lovely vitality.',
      'Applies sheer but can be layered to build desired color intensity, allowing for looks from natural to vibrant.',
    ],
    image: '/products/charlotte-tilbury-pillow-talk-lip-cheek-glow-colour-of-dreams.webp',
    coupangQuery: '샬롯 틸버리 필로우 토크 립 앤 치크 글로우',
    globalQuery: 'Charlotte Tilbury Pillow Talk Lip & Cheek Glow Colour of Dreams',
    clio: false,
    clioCategory: 'main',
    date: '2026-07-09',
    tags: ['multibalm', 'creamblush', 'lipandcheek', 'pillowtalk', 'charlottetilbury'],
  },
  {
    slug: 'rare-beauty-soft-pinch-liquid-blush',
    category: 'cheek',
    brand: 'Rare Beauty',
    name: 'Soft Pinch Liquid Blush',
    title: 'Rare Beauty Soft Pinch Liquid Blush: Selena Gomez\'s Touch for Vibrant Cheeks',
    summary:
      'Rare Beauty\'s best-selling liquid blush, loved for its amazing color payoff and lightweight feel. Just one or two drops create vibrant cheeks that last all day.',
    highlights: ['High pigmentation with a small amount', 'Available in matte/dewy finishes', 'Blends seamlessly without caking', 'Long-lasting wear'],
    details: [
      'A small amount delivers vivid color, making it easy to control intensity. Layer for desired color payoff.',
      'Available in two finishes, matte or dewy, allowing you to choose based on your desired makeup look.',
      'Adheres thinly to the skin, blending smoothly without caking or disturbing base makeup.',
      'Formulated with lotus, gardenia, and white water lily extracts to comfort the skin, providing excellent longevity for lasting color.',
    ],
    image: '/products/rare-beauty-soft-pinch-liquid-blush.webp',
    coupangQuery: '레어 뷰티 소프트 핀치 리퀴드 블러쉬',
    globalQuery: 'Rare Beauty Soft Pinch Liquid Blush',
    clio: false,
    clioCategory: 'cheek',
    date: '2026-07-09',
    tags: ['liquidblush', 'highlypigmentedblush', 'longlastingblush', 'selenagomezblush', 'sephorabestseller'],
  },
  {
    slug: 'espoir-pro-tailor-be-velvet-cover-cushion-new-class',
    category: 'base',
    brand: 'espoir',
    name: 'Pro Tailor Be Velvet Cover Cushion New Class',
    title: 'espoir Be Velvet Cushion: Thin, Flawless, Perfect Cover',
    summary:
      'A velvet matte cushion that adheres thinly and lightly, perfectly covering skin imperfections and maintaining a long-lasting finish without caking.',
    highlights: ['Thin, dense, flawless cover', 'Triple-layer ultra-adherence', 'Velvet matte finish', 'High-efficacy skincare ingredients'],
    details: [
      'High-definition powder, 59% finer than before, thinly and densely covers pores and uneven texture for smooth skin.',
      'A reinforced triple-layer film former with an added flexible film layer provides strong, fixer-like staying power, minimizing mask transfer.',
      'The soft, velvet-like semi-matte texture adheres comfortably to the skin, allowing for natural-looking skin even when reapplied without looking thick.',
      'Contains high-efficacy skincare ingredients for comfortable use on sensitive skin, and is certified vegan by EVE Vegan in France.',
    ],
    image: '/products/espoir-pro-tailor-be-velvet-cover-cushion-new-class.webp',
    coupangQuery: '에스쁘아 프로 테일러 비벨벳 커버 쿠션 뉴클래스',
    globalQuery: 'Espoir Pro Tailor Be Velvet Cover Cushion New Class',
    clio: true,
    clioCategory: 'base',
    date: '2026-07-09',
    tags: ['cushion', 'semimatte', 'highcover', 'longlastingcushion', 'veganbeauty'],
  },
  {
    slug: 'kaja-beauty-bento-bouncy-shimmer-eyeshadow-trio-orange-blossom',
    category: 'eye',
    brand: 'Kaja',
    name: 'Beauty Bento Bouncy Shimmer Eyeshadow Trio',
    title: 'Kaja Beauty Bento: Luminous Shimmer Eyes for a Flawless Look',
    summary:
      'This eyeshadow palette features three shimmery shades in a portable, 3-tiered bento box design, perfect for creating radiant and glamorous eye looks anytime, anywhere.',
    highlights: ['Buttery-smooth application', 'Minimal fallout shimmer pearls', 'Vivid color pigment', 'Mini, travel-friendly size'],
    details: [
      'The creamy powder texture applies easily and smoothly with fingers, adhering well to minimize fallout.',
      'Harmoniously composed with various undertone colors, it can be used alone or layered for diverse looks.',
      'High-adherence shimmer pearls deliver noticeable color payoff and sparkle, with a moist feel for a smooth, glossy finish.',
      'The small, cute bento box packaging is easy to carry, and the built-in mirror allows for touch-ups anytime.',
    ],
    image: '/products/kaja-beauty-bento-bouncy-shimmer-eyeshadow-trio-orange-blossom.webp',
    coupangQuery: '카자 뷰티 벤토 쉬머 아이섀도우',
    globalQuery: 'Kaja Beauty Bento Bouncy Shimmer Eyeshadow Trio Orange Blossom',
    clio: false,
    clioCategory: 'eye',
    date: '2026-07-09',
    tags: ['shimmer eyeshadow', 'daily makeup', 'portable', 'glitter'],
  },
  {
    slug: 'romand-lip-matter',
    category: 'lip',
    brand: 'rom&nd',
    name: 'Lip Matter',
    title: 'rom&nd Lip Matter: Transform Any Lip into a Velvety Matte Finish! Doubles as a Lip Primer',
    summary:
      'A new concept lip matter that transforms even dewy lip products into a soft, matte finish. Fills in fine lines for a smooth, blurred lip look.',
    highlights: ['Matte Lip Maker', 'Lip Wrinkle Cover', 'Soft, Powdery Finish', 'Primer Effect'],
    details: [
      'A unique formula that, when applied over any lipstick, creates a silky, powdery matte lip without greasiness.',
      'Fills in fine lines on the lips for a smooth, even lip makeup, creating a blurred effect.',
      'Contains moisturizing ingredients like palm seed butter, mango seed butter, and avocado oil for a comfortable finish without dryness.',
    ],
    image: '/products/romand-lip-matter.webp',
    coupangQuery: '롬앤 립 매터',
    globalQuery: 'romand lip matter',
    clio: true,
    clioCategory: 'lip',
    date: '2026-07-08',
    tags: ['rom&nd', 'LipMatter', 'MatteLip', 'LipPrimer', 'SoftLip'],
  },
  {
    slug: 'naming-high-dew-lip-glaze',
    category: 'lip',
    brand: 'NAMING.',
    name: 'HIGH DEW LIP GLAZE',
    title: 'NAMING. HIGH DEW LIP GLAZE: Achieve Plump Overlips Without Procedures!',
    summary:
      'This lip glaze features a clear, transparent syrup glaze texture that melts moistly onto lips, creating a plump and voluminous look. Its clear color remains even with multiple applications, without clumping.',
    highlights: ['Clear Syrup Glaze', 'Creates Plump Overlips', 'Clear Color Even When Layered', 'Non-Sticky Moisture'],
    details: [
      'The syrup glaze texture delivers extreme shine, adhering lightly and moistly to lips without feeling heavy or sticky.',
      'It melts smoothly onto lips, providing a natural plumping effect that creates plump, voluminous overlips without the need for cosmetic procedures.',
      'Available in 8 diverse colors, from clear vintage pink to mysterious mauve plum, allowing you to create vibrant and captivating lip makeup tailored to your skin tone.',
      'The transparent and vivid color is maintained even with multiple applications without clumping, blending with your natural lip color for a more natural look.',
    ],
    image: '/products/naming-high-dew-lip-glaze.webp',
    coupangQuery: '네이밍 하이 듀 립 글레이즈',
    globalQuery: 'naming high dew lip glaze',
    clio: true,
    clioCategory: 'lip',
    date: '2026-07-08',
    tags: ['GlazeTint', 'SyrupGlow', 'Overlip', 'Plumping', 'MoistTint'],
  },
  {
    slug: 'dinto-bare-gloss',
    category: 'lip',
    brand: 'Dinto',
    name: 'Bare-Gloss',
    title: 'Dinto Bare-Gloss: Transparent Shine & Vivid Color in One!',
    summary:
      'Dinto Bare-Gloss is a lip product that combines transparent gloss with the vivid color payoff of a tint. It enhances your natural lip color for a clear and lively lip makeup look.',
    highlights: ['Transparent shine', 'Vivid color payoff', 'Non-sticky melting texture', 'Natural-looking colors'],
    details: [
      'Experience both the transparent shine of a lip gloss and the vivid color of a lip tint simultaneously.',
      'Glides on smoothly, melting onto lips for a comfortable, non-sticky finish.',
      'Features medium-brightness and saturation colors that enhance your natural lip tone for a clear and lively look.',
      'This is the first lip makeup line from the \'Gumiho Collection,\' reinterpreting the traditional Korean folklore of the \'Gumiho\' (nine-tailed fox).',
    ],
    image: '/products/dinto-bare-gloss.webp',
    coupangQuery: '딘토 베어글로스',
    globalQuery: 'Dinto Bare Gloss',
    clio: true,
    clioCategory: 'lip',
    date: '2026-07-08',
    tags: ['Gloss', 'Lip Tint', 'Transparent Shine', 'Daily Lip'],
  },
  {
    slug: 'romnd-glasting-water-tint-sample',
    category: 'lip',
    brand: 'rom&nd',
    name: 'Glasting Water Tint',
    title: 'rom&nd Glasting Water Tint — Glassy, Dewy Water Lip',
    summary:
      'A water tint that glides on thin as water yet leaves a glassy shine. Layers without feeling heavy, so it works as a daily lip.',
    highlights: ['Glassy dewy finish', 'Thin, weightless glide', 'Everyday MLBB shade'],
    details: [
      'A watery, hydrating base layers thinly without clumping for natural, buildable color.',
      'A glassy, dewy glossy finish adds a plump, glossy look to the lips.',
      'Shades range from everyday MLBB tones to vivid reds, so there’s a pick for every taste.',
      'Less drying — it also works layered lightly over lip balm for a dewy glass-lip look.',
    ],
    image: '/products/romnd-glasting-water-tint-sample.webp',
    coupangQuery: '롬앤 글래스팅 워터 틴트',
    globalQuery: 'rom&nd Glasting Water Tint',
    clio: true,
    clioCategory: 'lip',
    date: '2026-07-08',
    tags: ['Lip tint', 'Dewy lip', 'Daily'],
    featured: true,
  },
]

export function getProductBySlugEn(slug: string): ProductPost | undefined {
  return PRODUCT_ITEMS_EN.find((p) => p.slug === slug)
}
