import type { ProductPost } from './types'

// 메이크업 제품 (Makeup Products) — Korean feed.
// New items are prepended daily by scripts/gen-products.mjs. Keep the newest on
// top (the generator inserts right after the array-open anchor below).
export const PRODUCT_ITEMS: ProductPost[] = [
  {
    slug: 'rare-beauty-soft-pinch-liquid-blush',
    category: 'cheek',
    brand: '레어 뷰티',
    name: '소프트 핀치 리퀴드 블러쉬',
    title: '레어 뷰티 소프트 핀치 리퀴드 블러쉬: 셀레나 고메즈의 터치로 물든 생기 가득 치크',
    summary:
      '놀라운 발색력과 가벼운 사용감으로 사랑받는 레어 뷰티의 베스트셀러 리퀴드 블러쉬. 한두 방울만으로도 하루 종일 지속되는 생기 넘치는 치크를 연출할 수 있습니다.',
    highlights: ['소량으로 고발색', '매트/촉촉 두 가지', '뭉침 없이 블렌딩', '오랜 지속력'],
    details: [
      '소량만으로도 선명한 컬러가 발색되어 양 조절이 용이하며, 덧바를수록 원하는 농도를 표현할 수 있습니다.',
      '매트 또는 듀이(촉촉) 두 가지 피니쉬로 출시되어 원하는 메이크업 룩에 따라 선택 가능합니다.',
      '피부에 얇게 밀착되어 뭉침 없이 부드럽게 블렌딩되며, 베이스 메이크업을 밀리게 하지 않습니다.',
      '연꽃, 치자, 흰 수련 추출물이 함유되어 피부를 편안하게 해주며, 뛰어난 지속력으로 컬러가 오래 유지됩니다.',
    ],
    image: '/products/rare-beauty-soft-pinch-liquid-blush.webp',
    coupangQuery: '레어 뷰티 소프트 핀치 리퀴드 블러쉬',
    globalQuery: 'Rare Beauty Soft Pinch Liquid Blush',
    clio: false,
    clioCategory: 'cheek',
    date: '2026-07-09',
    tags: ['리퀴드블러셔', '고발색블러셔', '지속력좋은블러셔', '셀레나고메즈블러셔', '세포라베스트셀러'],
  },
  {
    slug: 'espoir-pro-tailor-be-velvet-cover-cushion-new-class',
    category: 'base',
    brand: '에스쁘아',
    name: '프로 테일러 비벨벳 커버 쿠션 뉴클래스',
    title: '에스쁘아 비벨벳 쿠션, 얇고 완벽한 갓벽 커버',
    summary:
      '얇고 가볍게 밀착되어 피부 결점을 완벽하게 커버하며, 오랜 시간 무너짐 없이 유지되는 벨벳 매트 쿠션입니다.',
    highlights: ['얇고 촘촘한 갓벽 커버', '트리플 레이어 초밀착', '벨벳 매트 피니쉬', '고효능 스킨케어 성분'],
    details: [
      '기존 대비 59% 미세해진 하이데피니션 파우더가 모공과 요철을 얇고 촘촘하게 커버하여 매끈한 피부를 연출합니다.',
      '유연한 필름막을 한 겹 더 강화한 트리플 레이어 필름 포머가 픽서로 고정한 듯 강력한 지속력을 선사하며, 마스크 묻어남을 최소화합니다.',
      '벨벳처럼 부드러운 세미 매트 텍스처가 피부에 편안하게 밀착되어 덧발라도 두꺼워지지 않고 자연스러운 피부 표현이 가능합니다.',
      '고효능 스킨케어 성분을 함유하여 민감한 피부도 편안하게 사용할 수 있으며, 프랑스 이브 비건 인증을 받은 제품입니다.',
    ],
    image: '/products/espoir-pro-tailor-be-velvet-cover-cushion-new-class.webp',
    coupangQuery: '에스쁘아 프로 테일러 비벨벳 커버 쿠션 뉴클래스',
    globalQuery: 'Espoir Pro Tailor Be Velvet Cover Cushion New Class',
    clio: true,
    clioCategory: 'base',
    date: '2026-07-09',
    tags: ['쿠션', '세미매트', '고커버', '지속력좋은쿠션', '비건화장품'],
  },
  {
    slug: 'kaja-beauty-bento-bouncy-shimmer-eyeshadow-trio-orange-blossom',
    category: 'eye',
    brand: '카자',
    name: '뷰티 벤토 바운시 쉬머 아이섀도우 트리오',
    title: '카자 뷰티 벤토, 뭉침 없이 반짝이는 영롱한 쉬머 아이메이크업',
    summary:
      '휴대하기 좋은 3단 벤토 상자 디자인에 3가지 쉬머 섀도우가 담겨 언제 어디서든 영롱하고 화려한 눈매를 연출할 수 있는 아이섀도우 팔레트입니다.',
    highlights: ['버터처럼 부드러운 발림성', '가루 날림 적은 쉬머 펄', '생생한 컬러 피그먼트', '휴대하기 좋은 미니 사이즈'],
    details: [
      '크리미한 파우더 제형으로 손가락으로 쉽고 부드럽게 발리며, 밀착력이 좋아 가루 날림이 적습니다.',
      '다양한 언더톤의 컬러들이 조화롭게 구성되어 단독으로 사용하거나 여러 겹 레이어링하여 다채로운 룩을 연출할 수 있습니다.',
      '고밀착 쉬머 펄이 눈에 띄는 발색과 반짝임을 선사하며, 촉촉한 사용감으로 매끄럽고 윤기 있는 마무리를 연출합니다.',
      '작고 귀여운 벤토 상자 패키지로 휴대가 간편하며, 내장된 거울로 언제든 수정 화장이 가능합니다.',
    ],
    image: '/products/kaja-beauty-bento-bouncy-shimmer-eyeshadow-trio-orange-blossom.webp',
    coupangQuery: '카자 뷰티 벤토 쉬머 아이섀도우',
    globalQuery: 'Kaja Beauty Bento Bouncy Shimmer Eyeshadow Trio Orange Blossom',
    clio: false,
    clioCategory: 'eye',
    date: '2026-07-09',
    tags: ['쉬머아이섀도우', '데일리메이크업', '휴대용', '글리터'],
  },
  {
    slug: 'romand-lip-matter',
    category: 'lip',
    brand: '롬앤',
    name: '립 매터',
    title: '롬앤 립 매터, 어떤 립도 보송 매트립으로! 입술 프라이머 겸용',
    summary:
      '촉촉한 립 제품도 보송한 매트 립으로 변신시켜주는 신개념 립 매터. 입술 잔주름을 메꿔주어 매끈하고 블러 처리한 듯한 립 표현을 완성합니다.',
    highlights: ['매트립 메이커', '입술 주름 커버', '보송한 마무리', '프라이머 효과'],
    details: [
      '어떤 립스틱이든 덧바르면 기름기 없이 실키하고 보송한 매트립으로 연출해주는 신박한 제형입니다.',
      '입술에 블러 처리한 듯 잔주름을 메꿔주어 매끈하고 균일한 립 메이크업을 도와줍니다.',
      '야자씨드버터, 망고씨드버터, 아보카도 오일 등 보습 성분을 함유하여 건조함 없이 편안하게 마무리됩니다.',
    ],
    image: '/products/romand-lip-matter.webp',
    coupangQuery: '롬앤 립 매터',
    globalQuery: 'romand lip matter',
    clio: true,
    clioCategory: 'lip',
    date: '2026-07-08',
    tags: ['롬앤', '립매터', '매트립', '립프라이머', '보송립'],
  },
  {
    slug: 'naming-high-dew-lip-glaze',
    category: 'lip',
    brand: '네이밍',
    name: '하이 듀 립 글레이즈',
    title: '네이밍 하이 듀 립 글레이즈: 시술 없이도 통통한 오버립 연출!',
    summary:
      '맑고 투명한 시럽 글레이즈 텍스처가 입술에 촉촉하게 녹아들어 탱글하고 볼륨감 있는 립을 연출해주는 립 글레이즈입니다. 여러 번 덧발라도 뭉침 없이 맑은 컬러감이 특징입니다.',
    highlights: ['맑은 시럽 글레이즈', '탱글한 오버립 연출', '덧발라도 맑은 컬러', '끈적임 없는 촉촉함'],
    details: [
      '극광의 광택을 선사하는 시럽 글레이즈 텍스처로, 답답함이나 끈적임 없이 가볍고 촉촉하게 입술에 밀착됩니다.',
      '입술에 부드럽게 녹아들어 자연스럽게 차오르는 플럼핑 효과로 시술 없이도 통통하고 볼륨감 있는 오버립을 연출할 수 있습니다.',
      '맑은 톤의 빈티지 핑크부터 오묘한 모브 플럼까지, 다채로운 8가지 컬러로 출시되어 피부 톤에 맞춰 생기 있고 매혹적인 립 메이크업을 연출할 수 있습니다.',
      '덧발라도 뭉침 없이 투명하고 선명한 컬러가 유지되며, 입술 본연의 색과 어우러져 더욱 자연스러운 발색을 자랑합니다.',
    ],
    image: '/products/naming-high-dew-lip-glaze.webp',
    coupangQuery: '네이밍 하이 듀 립 글레이즈',
    globalQuery: 'naming high dew lip glaze',
    clio: true,
    clioCategory: 'lip',
    date: '2026-07-08',
    tags: ['글레이즈틴트', '시럽광택', '오버립', '플럼핑', '촉촉한틴트'],
  },
  {
    slug: 'dinto-bare-gloss',
    category: 'lip',
    brand: '딘토',
    name: '베어글로스',
    title: '딘토 베어글로스, 투명한 광택과 선명한 발색을 한 번에!',
    summary:
      '딘토 베어글로스는 투명한 광택감과 틴트의 선명한 발색을 결합한 립 제품입니다. 입술 본연의 색감을 살려 맑고 생기 있는 립 메이크업을 연출해 줍니다.',
    highlights: ['투명한 광택', '선명한 발색', '끈적임 없는 멜팅', '자연스러운 컬러'],
    details: [
      '립글로스의 투명한 광택감과 립틴트의 선명한 발색을 동시에 느낄 수 있는 제품입니다.',
      '입술에 부드럽게 녹아들 듯 발리며, 끈적임 없이 편안한 마무리감을 선사합니다.',
      '입술 본연의 색감을 살리는 중간 명도와 채도의 컬러로 맑고 생기 있는 립을 연출합니다.',
      '한국 전통 설화 \'구미호\'를 재해석한 \'구미호 컬렉션\'의 첫 립 메이크업 라인입니다.',
    ],
    image: '/products/dinto-bare-gloss.webp',
    coupangQuery: '딘토 베어글로스',
    globalQuery: 'Dinto Bare Gloss',
    clio: true,
    clioCategory: 'lip',
    date: '2026-07-08',
    tags: ['글로스', '립틴트', '투명광택', '데일리립'],
  },
  {
    slug: 'romnd-glasting-water-tint-sample',
    category: 'lip',
    brand: '롬앤',
    name: '글래스팅 워터 틴트',
    title: '롬앤 글래스팅 워터 틴트 — 촉촉한 유리알 물광 립',
    summary:
      '물처럼 얇게 발리면서 유리알 같은 광을 남기는 워터 틴트. 겹발라도 답답하지 않아 데일리로 쓰기 좋아요.',
    highlights: ['유리알 물광 마무리', '얇고 가벼운 발림', 'MLBB 데일리 컬러'],
    details: [
      '수분감 있는 워터 베이스라 얇게 겹쳐 발라도 뭉치지 않고 자연스럽게 발색돼요.',
      '유리알처럼 촉촉하게 반짝이는 글로시 마무리로 입술에 볼륨감을 더해줍니다.',
      '데일리로 무난한 MLBB 톤부터 선명한 레드까지 컬러 구성이 다양해 취향대로 고르기 좋아요.',
      '건조함이 덜해 립밤 위에 가볍게 덧발라 촉촉한 물광 립으로 연출하기도 좋습니다.',
    ],
    image: '/products/romnd-glasting-water-tint-sample.webp',
    coupangQuery: '롬앤 글래스팅 워터 틴트',
    globalQuery: 'rom&nd Glasting Water Tint',
    clio: true,
    clioCategory: 'lip',
    date: '2026-07-08',
    tags: ['립 틴트', '물광 립', '데일리'],
    featured: true,
  },
]

export function getProductBySlug(slug: string): ProductPost | undefined {
  return PRODUCT_ITEMS.find((p) => p.slug === slug)
}
